### ISSUE TITLE
plot two lines 

### ISSUE THREAD

**Issue by kexul** [piccolomo/plotext#1]
How to plot two lines in the same time?

**Comment by piccolomo** [comment]
Thanks for the question kexul, for now only one line is allowed, I may add the option of multiple lines soon if it is requested. I will update

**Comment by madrian** [comment]
I have the same question. It would be good to have with different y axis range.

Overall, this tool is great and lightweight. It is good for quick analysis of data points. I'm trying to integrate it with another project. Thanks @piccolomo.

**Comment by piccolomo** [comment]
I actually found a way to plot multiple lines with different options. It will be available in the next version of the package, coming soon ... any other input is valuable, thanks

**Comment by piccolomo** [comment]
Hi Kezul and Madrian, I have finally updated the package and **you can now plot multiples lines**. There are also other changes. 

You can find the package at https://pypi.org/project/plotext/. 
Let me know what you think and if there are any other issues.

Thanks for your inputs,
Savino
