### ISSUE TITLE
Axes with wrong labels

### ISSUE THREAD

**Issue by Psychi1** [piccolomo/plotext#10]
Hi,

maybe I missunderstood the manual, but I expect a plot from x = 1 to 10 and values y from 1 to 100.

```python
import plotext as plx

x=[1,2,3,4,5,6,7,8,9,10]
y=[i**2 for i in x]
plx.scatter(x,y)
plx.show()
```

however I get a plot like the this one.

```
                                                                                                                    •├45
                                                                                                                     │  
                                                                                                                     │  
                                                                                                                     │  
                                                                                                                     │  
                                                                                                                     ├40
                                                                                                                     │  
                                                                                                                     │  
                                                                                                                     │  
                                                                                                       •             │  
                                                                                                                     ├35
                                                                                                                     │  
                                                                                                                     │  
                                                                                                                     │  
                                                                                                                     │  
                                                                                                                     ├30
                                                                                          •                          │  
                                                                                                                     │  
                                                                                                                     │  
                                                                                                                     │  
                                                                                                                     ├25
                                                                                                                     │  
                                                                                                                     │  
                                                                             •                                       │  
                                                                                                                     │  
                                                                                                                     ├20
                                                                                                                     │  
                                                                                                                     │  
                                                                                                                     │  
                                                                •                                                    │  
                                                                                                                     ├15
                                                                                                                     │  
                                                                                                                     │  
                                                                                                                     │  
                                                    •                                                                │  
                                                                                                                     ├10
                                                                                                                     │  
                                                                                                                     │  
                                       •                                                                             │  
                                                                                                                     │  
                                                                                                                     ├5 
                          •                                                                                          │  
                                                                                                                     │  
                                                                                                                     │  
             •                                                                                                       │  
•                                                                                                                    ├0 
┬─────────┬─────────┬─────────┬─────────┬─────────┬─────────┬─────────┬─────────┬─────────┬─────────┬─────────┬──────┘  
0         10        20        30        40        50        60        70        80        90        100       110       
```
The (x,y)-pairs are not matching with the labels on the axes.

What I'm doing wrong?

```python
>>> plx.__version__
'1.0.11'
>>> sys.version
'3.8.2 (tags/v3.8.2:7b3ab59, Feb 25 2020, 23:03:10) [MSC v.1916 64 bit (AMD64)]'
```

Bye, Uwe

**Comment by miraculixx** [comment]
Same issue, whatever the values, with or without setting ylim, xlim, the plot always comes out with the same axes labels, as shown above.

**Comment by piccolomo** [comment]
Hi Psychi1 and miraculixx, 

thanks for the issue reporting. That version of plotext does what intended. I have now updated the packed to version 2 which can better handles the axes ticks. 
Here is the code:

`import plotext as plt
plt.scatter(x, y)
plt.set_canvas_size(100, 30) # not necessary but it makes the plot easier to upload here
plt.show()
`
and here is the outputted plot:
`                                                                                                   •├ 99.8
                                                                                                    │     
                                                                                                    │     
                                                                                                    │     
                                                                                                    │     
                                                                                                    │     
                                                                                        •           │     
                                                                                                    ├ 75.1
                                                                                                    │     
                                                                                                    │     
                                                                                                    │     
                                                                             •                      │     
                                                                                                    │     
                                                                                                    │     
                                                                                                    │     
                                                                  •                                 ├ 50.4
                                                                                                    │     
                                                                                                    │     
                                                                                                    │     
                                                       •                                            │     
                                                                                                    │     
                                                                                                    │     
                                            •                                                       ├ 25.7
                                                                                                    │     
                                                                                                    │     
                                 •                                                                  │     
                                                                                                    │     
                      •                                                                             │     
           •                                                                                        │     
•                                                                                                   ├ 1.0 
┬────────────────────────┬────────────────────────┬───────────────────────┬────────────────────────┬┘     
1                        3.25                     5.5                     7.75                     10     
                                                                      y = + 1.0020243 × y_tick - 0.0020243`

You can upgrade your plotext version using `sudo -H pip install plotext --upgrade`.

**Comment by piccolomo** [comment]
> Hi,
> 
> maybe I missunderstood the manual, but I expect a plot from x = 1 to 10 and values y from 1 to 100.
> 
> ```python
> import plotext as plx
> 
> x=[1,2,3,4,5,6,7,8,9,10]
> y=[i**2 for i in x]
> plx.scatter(x,y)
> plx.show()
> ```
> 
> however I get a plot like the this one.
> 
> ```
>                                                                                                                     •├45
>                                                                                                                      │  
>                                                                                                                      │  
>                                                                                                                      │  
>                                                                                                                      │  
>                                                                                                                      ├40
>                                                                                                                      │  
>                                                                                                                      │  
>                                                                                                                      │  
>                                                                                                        •             │  
>                                                                                                                      ├35
>                                                                                                                      │  
>                                                                                                                      │  
>                                                                                                                      │  
>                                                                                                                      │  
>                                                                                                                      ├30
>                                                                                           •                          │  
>                                                                                                                      │  
>                                                                                                                      │  
>                                                                                                                      │  
>                                                                                                                      ├25
>                                                                                                                      │  
>                                                                                                                      │  
>                                                                              •                                       │  
>                                                                                                                      │  
>                                                                                                                      ├20
>                                                                                                                      │  
>                                                                                                                      │  
>                                                                                                                      │  
>                                                                 •                                                    │  
>                                                                                                                      ├15
>                                                                                                                      │  
>                                                                                                                      │  
>                                                                                                                      │  
>                                                     •                                                                │  
>                                                                                                                      ├10
>                                                                                                                      │  
>                                                                                                                      │  
>                                        •                                                                             │  
>                                                                                                                      │  
>                                                                                                                      ├5 
>                           •                                                                                          │  
>                                                                                                                      │  
>                                                                                                                      │  
>              •                                                                                                       │  
> •                                                                                                                    ├0 
> ┬─────────┬─────────┬─────────┬─────────┬─────────┬─────────┬─────────┬─────────┬─────────┬─────────┬─────────┬──────┘  
> 0         10        20        30        40        50        60        70        80        90        100       110       
> ```
> 
> The (x,y)-pairs are not matching with the labels on the axes.
> 
> What I'm doing wrong?
> 
> ```python
> >>> plx.__version__
> '1.0.11'
> >>> sys.version
> '3.8.2 (tags/v3.8.2:7b3ab59, Feb 25 2020, 23:03:10) [MSC v.1916 64 bit (AMD64)]'
> ```
> 
> Bye, Uwe
