### ISSUE TITLE
Images not working

### ISSUE THREAD

**Issue by mattAndruff** [piccolomo/plotext#101]
Images are looking funky/chunky.

I download plotext 5.0(via conda) on Centos 7 (Python 3.7.12)
`conda install plotext[image] --force`

<img width="1440" alt="Screen Shot 2022-07-18 at 8 49 55 AM" src="https://user-images.githubusercontent.com/26882428/179515280-e34506e8-a342-4f2a-a684-a23b6f8d6aa7.png">

Tried downloading 5.1 from git but it was dropping a syntax error. So I reverted to 5.0.

Any suggestions?

```
conda list
# packages in environment at /home/trubble/anaconda3/envs/face-the-same:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                  2_kmp_llvm    conda-forge
alsa-lib                  1.2.6.1              h7f98852_0    conda-forge
aom                       3.3.0                h27087fc_1    conda-forge
blas                      2.115                       mkl    conda-forge

--- Table shortened by @piccolomo 


zipp                      3.8.0              pyhd8ed1ab_0    conda-forge
zlib                      1.2.12               h166bdaf_1    conda-forge
zlib-ng                   2.0.6                h166bdaf_0    conda-forge
zstd                      1.5.2                h8a70e8d_1    conda-forge
```

**Comment by piccolomo** [comment]
Hi @mattAndruff , I finally updated `plotext` and the new version should solve this issue. 

The new version is available [on GitHib](https://github.com/piccolomo/plotext) for now and soon also [on PyPi](https://pypi.org/project/plotext/). To install follow the indications [here](https://github.com/piccolomo/plotext#install).

Any feedback is welcomed.

Thanks a lot for your inputs and all the best,
Savino
