### ISSUE TITLE
Question: X Axis Label

### ISSUE THREAD

**Issue by SkyHyperV** [piccolomo/plotext#102]
I have a list I'm passing into the bar chart but it ends up looking like below. I want to keep the whole numbers and have each tick labeled with the entries in the list. I tried the xticks function but not sure how to use it properly:

Essentially, the X-axis are "Weeks", so I need it 1, 2, 3, ... instead of thee floating point it seems to be attempting to distribute across the X-axis.

![image](https://user-images.githubusercontent.com/31451171/179524232-8190c6fd-098e-4a49-a14d-4a654098ba1a.png)

**Comment by piccolomo** [comment]
Hi @SkyHyperV , I finally updated `plotext` and the new version should solve this issue automatically. 

The new version is available [on GitHib](https://github.com/piccolomo/plotext) for now and soon also [on PyPi](https://pypi.org/project/plotext/). To install follow the indications [here](https://github.com/piccolomo/plotext#install).

Any feedback is welcomed. Please report if the issue persists. 

Thanks a lot for your inputs and all the best,
Savino
