### ISSUE TITLE
Range based on list contents

### ISSUE THREAD

**Issue by SkyHyperV** [piccolomo/plotext#103]
I have tried the following snippet of code and I get the range (26, 29) but for some reason the labels are not printing.

The snippet you gave me earlier worked great for my lists which were 1 ... n, but when I have a list of just [27, 28, 29], I'm not sure how to get the xticks/xlabel to work with you library?

        xticks = range(week_int[0]-1, week_int[-1]+1)
        xlabels = [str(el) for el in xticks]
        print(xticks)
        print(xlabels)
        plt.xticks(xticks, xlabels)

**Comment by SkyHyperV** [comment]
See another example with the same list with value 7 and '7' label -- one graph shows the 7 single-tick and the other graph is missing the label.

![image](https://user-images.githubusercontent.com/31451171/179655298-0bf80eb0-cb0b-4a9e-93d8-f0c13fb44891.png)

**Comment by SkyHyperV** [comment]
Also just to update, I updated to 5.1 and the graph is still not having the single tick whereas another graph does.

**Comment by SkyHyperV** [comment]
I see why the stacked one has a tick, I was passing in the 'month' list to one graph but not the other. The default bar examples dont show this and I completely missed it. Will close as its fixed now.

**Comment by piccolomo** [comment]
Hi @SkyHyperV , I finally updated `plotext` and the new version should solve this issue automatically. 

The new version is available [on GitHib](https://github.com/piccolomo/plotext) for now and soon also [on PyPi](https://pypi.org/project/plotext/). To install follow the indications [here](https://github.com/piccolomo/plotext#install).

Any feedback is welcomed. Please report if the issue persists. 

Thanks a lot for your inputs and all the best,
Savino
