### ISSUE TITLE
Plot Colors not Rendered in Windows

### ISSUE THREAD

**Issue by SkyHyperV** [piccolomo/plotext#105]
Is there a way to make Windows command prompt show the colored graphs? It's showing grey for all my users but works nicely for me in Linux shell.

**Comment by piccolomo** [comment]
Hi @SkyHyperV , I finally updated `plotext` and the new version should solve this issue. 

The new version is available [on GitHib](https://github.com/piccolomo/plotext) for now and soon also [on PyPi](https://pypi.org/project/plotext/). To install follow the indications [here](https://github.com/piccolomo/plotext#install).

Any feedback is welcomed. Please report if the issue persists. 

Thanks a lot for your inputs and all the best,
Savino
