### ISSUE TITLE
Incorrect text using text on bar plots

### ISSUE THREAD

**Issue by pankajp** [piccolomo/plotext#106]
As in the example https://github.com/piccolomo/plotext/blob/master/readme/other.md#text-plot 
The labels Mu**s**hrooms and Chee**s**e are missing the **s**

```
python3 -c "import plotext as plt; pizzas = ['Sausage', 'Pepperoni', 'Mushrooms', 'Cheese', 'Chicken', 'Beef']; percentages = [14, 36, 11, 8, 7, 4]; plt.bar(pizzas, percentages); plt.title('Labelled Bar Plot using Text()'); [plt.text(pizzas[i], x = pizzas[i], y = percentages[i] + 1.5, alignment = 'center', color = 'red') for i in range(len(pizzas))]; plt.ylim(0, 38); plt.plotsize(100, 30); plt.show()"
```

![image](https://user-images.githubusercontent.com/776111/180268807-ee02803d-dd6d-4d18-9406-601d6663bda1.png)

**Comment by piccolomo** [comment]
Hi @pankajp , I finally updated `plotext` and the new version should solve this issue. 

Your changes are documented [here](https://github.com/piccolomo/plotext/blob/master/readme/other.md#text-plot) 

The new version is available [on GitHib](https://github.com/piccolomo/plotext) for now and soon also [on PyPi](https://pypi.org/project/plotext/). To install follow the indications [here](https://github.com/piccolomo/plotext#install).

Any feedback is welcomed. Please report if the issue persists. 

Thanks a lot for your inputs and all the best,
Savino
