### ISSUE TITLE
Request: Square Wave Plot

### ISSUE THREAD

**Issue by vps-eric** [piccolomo/plotext#108]
Hello,
This is a great project! One useful plot to add would be that of a square wave:

![image](https://user-images.githubusercontent.com/65966889/182431125-ac27e682-71d2-4a83-9b70-42512915cc1d.png)
Example from the SciPy project.

I realize this could probably be done using the standard `plot()`, but a convenience function for this would be great (or an example in the docs).

**Comment by piccolomo** [comment]
Good idea, I should come up with something ..

**Comment by piccolomo** [comment]
Hello @vps-eric,

Here is the result:
![image](https://user-images.githubusercontent.com/56689657/187881061-e8a70cb5-f34a-4ebb-a051-27bfcd8df6e0.png)

I will upload the code soon. Any feedback welcomed. Thanks! :-)

**Comment by vps-eric** [comment]
Fantastic, thank you!

**Comment by piccolomo** [comment]
Hi @vps-eric , I finally updated `plotext` including the changes you asked for. 

I introduced the function `square()`, but haven't tested properly so any feedback is welcomed. 

The new version is available [on GitHib](https://github.com/piccolomo/plotext) for now and soon also [on PyPi](https://pypi.org/project/plotext/). To install follow the indications [here](https://github.com/piccolomo/plotext#install).

Your changes are documented [here](https://github.com/piccolomo/plotext/blob/master/readme/utilities.md#useful-functions) and you have been credited [here](https://github.com/piccolomo/plotext/blob/master/readme/notes.md#credits).

Any feedback is welcomed.

Thanks a lot for your inputs and all the best,
Savino
