### ISSUE TITLE
Request: Allow appending to file with savefig()

### ISSUE THREAD

**Issue by dns13** [piccolomo/plotext#109]
savefig() opens the file as 'w+', an option to set file mode to 'a+' to append to that file would be great.

**Comment by piccolomo** [comment]
Hi @dns13 , I finally updated `plotext` including the changes you asked for. 

I introduced the parameter `append` in the `save_fig()` function but haven't tested properly so any feedback is welcomed. 

The new version is available [on GitHib](https://github.com/piccolomo/plotext) for now and soon also [on PyPi](https://pypi.org/project/plotext/). To install follow the indications [here](https://github.com/piccolomo/plotext#install).

Your changes are documented [here](https://github.com/piccolomo/plotext/blob/master/readme/utilities.md#useful-functions) and you have been credited [here](https://github.com/piccolomo/plotext/blob/master/readme/notes.md#credits).

Any feedback is welcomed.

Thanks a lot for your inputs and all the best,
Savino

**Comment by dns13** [comment]
Thank you, working like a charm for me.
