### ISSUE TITLE
That repo history...

### ISSUE THREAD

**Issue by abitrolly** [piccolomo/plotext#11]
...is very unusual.

@piccolomo are out syncing it from other version control system?

**Comment by piccolomo** [comment]
I don't think I understand the question.

**Comment by abitrolly** [comment]
In `git` history this project is only 4 days old - https://github.com/piccolomo/plotext/commits/master

**Comment by piccolomo** [comment]
So what is the problem with that ?!

**Comment by piccolomo** [comment]
So what is the problem with that ?!
- Savino

**Comment by abitrolly** [comment]
The project at PyPI is much older https://pypi.org/project/plotext/#history

**Comment by piccolomo** [comment]
I have no solution for empty suspiciousness ... Issue closed! 

All the best

**Comment by abitrolly** [comment]
Is there a reason to be suspicious?

Or do you imply that you've hacked this account and now it should look suspicious, because you hide some traces of hideous trojan code that was injected in the previous versions? :D

**Comment by piccolomo** [comment]
How about respectfully alerting that you have found some of that code, instead of throwing accusations? 

I will check the code, but tone down the attitude and be respectful !

**Comment by abitrolly** [comment]
Calm down. I am not going to use your code after all. Just curious what causes the replacement of history. It could be an automation from different source control system, or a simplified pipeline for sight impaired users.

**Comment by piccolomo** [comment]
(non) Issue closed!

**Comment by abitrolly** [comment]
You can also make it read-only.

(That will raise the suspicion, of course..)

**Comment by abitrolly** [comment]
Yep, and that didn't asnwer the question why anyone would need to erase the history every time.
