### ISSUE TITLE
Hide ticks

### ISSUE THREAD

**Issue by S1SYPHOS** [piccolomo/plotext#110]
Hey there,
would it be possible to completely hide ticks? I tried something like `plt.ticks_color(None)` which didn't yield the desired effect - worth a try though :grin: I want to hide them and only label the bars of my bar chart, but I can totally see that this is somewhat of an edge case :confused:

**Comment by piccolomo** [comment]
No, it totally doable, try the function `xfrequency(0)` or `yfrequency(0)`, did it help?

**Comment by S1SYPHOS** [comment]
I'll try and report back. Quick aside: "official" support of labelled bars would be great, but that's maybe something for another issue 😃

**Comment by S1SYPHOS** [comment]
@piccolomo yeah ticks are hidden, but how do I get rid of the box around it? When changing tick color, border/axis color is changed too - I suspected that "disabling" ticks would remove them / the surrounding rectangle. One thing: setting `plt.xticks([])` & `plt.yticks([])` has the same effect 😀

**Comment by piccolomo** [comment]
Hi @S1SYPHOS, try` plt.frame(False)` or the functions` plt.xaxes()` and  `plt.yaxes()` for full control over each axes.

Ye `plt.xticks([])` and `plt.yticks([])` have the same effect as `plt.xfrequency(0)` or `plt.yfrequency(0)`, but the former functions give you more control, the latter quicker ability to change just the ticks frequency.

**Comment by S1SYPHOS** [comment]
`frame(False)` was exactly what I needed - I had tried `None` before and it didn't work :)

**Comment by piccolomo** [comment]
Hi @S1SYPHOS , I finally updated `plotext` and the new version should solve this issue. 

The new version is available [on GitHib](https://github.com/piccolomo/plotext) for now and soon also [on PyPi](https://pypi.org/project/plotext/). To install follow the indications [here](https://github.com/piccolomo/plotext#install).

Any feedback is welcomed. Please report if the issue persists. 

Thanks a lot for your inputs and all the best,
Savino

**Comment by S1SYPHOS** [comment]
Hey there @piccolomo,
installing the updated version, I am now greeted with: `ModuleNotFoundError: No module named 'shtab'` which - from your code inside `plotext/plotext_cli.py:5` is required, but only listed as `optional` dependency. Since I only installed `plotext`, this now fails my `pytest` :grinning:

**Comment by piccolomo** [comment]
Hi @S1SYPHOS , thanks a lot for letting me know I have updated both the github and pypi version and the problem should be solved. Any double checking is welcomed. Thanks!
