### ISSUE TITLE
Configure space between axes & plotted data as well as between multiple bars

### ISSUE THREAD

**Issue by S1SYPHOS** [piccolomo/plotext#111]
Hey there,

as you can see, the space between the bar and the yticks is kind of small :smile: is there a way to increase it? And also, I would like a way to force multiple bars to stay close to another!

![image](https://user-images.githubusercontent.com/12161504/183725159-025eca16-534e-48e6-ae3f-5e5d1803e857.png)

Thanks and btw: I LOVE this library!
Cheers,
S1SYPHOS

**Comment by piccolomo** [comment]
hello no problem ask as much as you want. the only thing i may not be able to upgrade the package anytime soon, other then that questions don't bother me. 

in this case i would suggest the function plt.xlim(left, right)... but in one of the previous issues there seem to be a problem with it... you need to set both limits left and right on the x axis and not just one, and it should work.

did it help?

**Comment by S1SYPHOS** [comment]
this seems to alter the values being displayed, not the "physical" distance / space between the y-axis and the first bar .. :confused:

**Comment by piccolomo** [comment]
it should not if you use plt.xlim and not plt.ylim in you case.

another option is to use plt.yaxes(1,1) after plt.frame(0) and make the color of the axes transparent,  with plt.ticks_color ... i cant remember the color to make it transparent. maybe black or clear... have a look at plt.colors()

**Comment by S1SYPHOS** [comment]
Thanks so much, will investigate further ;)

**Comment by piccolomo** [comment]
Here is an example with function xlim(), code is above the plot.
![image](https://user-images.githubusercontent.com/56689657/183745654-c9a7c487-8ec0-4e45-ac33-48b3c840c639.png)

**Comment by S1SYPHOS** [comment]
I'm trying to get the pairs (multi-pair) more closely together, how could I do that? Your example uses three single-bars 😀

**Comment by piccolomo** [comment]
it should be as easy as using multiple_bar() instead of bar(). if you have difficulties, send me a working code and i could tweak it.

**Comment by piccolomo** [comment]
Oh and I forgot to add: try increase the `width` parameter of `multiple_bar()` closer to one. Did it work?

**Comment by S1SYPHOS** [comment]
Well, my example above is already using `multi_bar` 😃

**Comment by piccolomo** [comment]
you could try the `width` parameter and if you don't manage, feel free to send an initial working code and i could tweak it.

**Comment by S1SYPHOS** [comment]
I want to move the bar pairs closer together AND configure the space between each pair WHILE maintaining their width! 😮

**Comment by piccolomo** [comment]
then other then the `width` parameter, you could try to change the coordinates x of each pair so that they are further apart.

**Comment by S1SYPHOS** [comment]
Thanks! Will experiment some more and report back.

**Comment by piccolomo** [comment]
Hi @S1SYPHOS , I finally updated `plotext` and the new version should solve this issue. 

The new version is available [on GitHib](https://github.com/piccolomo/plotext) for now and soon also [on PyPi](https://pypi.org/project/plotext/). To install follow the indications [here](https://github.com/piccolomo/plotext#install).

Any feedback is welcomed. Please report if the issue persists. 

Thanks a lot for your inputs and all the best,
Savino
