### ISSUE TITLE
Feature Request: Confusion Matrix

### ISSUE THREAD

**Issue by 3h4** [piccolomo/plotext#113]
Amazing library! Would it be possible to plot a confusion matrix? Perhaps I can do it with the matrix_plot and then put text on top of that?

**Comment by piccolomo** [comment]
Thanks for the appreciation:-) 

Would that be the confusion matrix connected to machine learning?

**Comment by 3h4** [comment]
Yes indeed, that is the case :)

**Comment by piccolomo** [comment]
Thanks, will answer relatively soon!

**Comment by piccolomo** [comment]
Hi @3h4, finally working on your idea. Here is a partial result:

![image](https://user-images.githubusercontent.com/56689657/187900589-021dc80b-bbaa-4f83-ad71-fa8236231a41.png)

I will upload new code soon. Any feedback for now is welcomed.

Thanks

**Comment by 3h4** [comment]
@piccolomo Wow looks perfect! Would it be possible to have more classes than 2, for example 15 different animals or something like that? So you can put a percentage or number in the square and class on the axes. Perhaps there will be not enough room so only numbers can be used? Or single letters. Great work so far!

**Comment by piccolomo** [comment]
Hi @3h4 , I finally updated `plotext` including the changes you asked for. 

I introduced the function `confusion_matrix()`, but haven't tested properly so any feedback is welcomed. 

The new version is available [on GitHib](https://github.com/piccolomo/plotext) for now and soon also [on PyPi](https://pypi.org/project/plotext/). To install follow the indications [here](https://github.com/piccolomo/plotext#install).

Your changes are documented [here](https://github.com/piccolomo/plotext/blob/master/readme/matrix.md#confusion-matrix) and you have been credited [here](https://github.com/piccolomo/plotext/blob/master/readme/notes.md#credits).

Any feedback is welcomed.

Thanks a lot for your inputs and all the best,
Savino

**Comment by 3h4** [comment]
@piccolomo Omg, Perfect! Is it possible to put it in a subplot as well? What happens if the space becomes too small?

**Comment by piccolomo** [comment]
I think you can, if the space diminishes the plot tries its best to adapt, if too small some features disappear. Try it if you can and see if there are any issue. I really haven't played around it much. Thanks :-)

**Comment by piccolomo** [comment]
I was trying to get some nice blue shaded rectangles, as gray is a bit dull, but could not find a way around it. If anyone can please send some code. Thanks :-)
