### ISSUE TITLE
Feature Request: Better Handling Nan and None Values

### ISSUE THREAD

**Issue by Freed-Wu** [piccolomo/plotext#114]
```python
import plotext as plt
y = plt.sin()
import numpy as np
y[:40] = [np.nan] * 40
plt.scatter(y)
plt.show()
```

Expected: A plot which x range is `[0, 200]`, but `[0, 40]` don't have any number.

Actual: A plot which x range is `[40, 200]`.

**Comment by piccolomo** [comment]
Hi @Freed-Wu,

I am working on the issues. Regarding this one, no idea is coming to me on how to solve it. The function that I use to remove non numerical values litterally removes all of the non numerical values (nan or None).

```
non_numerical = lambda el:  el == None or (not isinstance(el, str) and math.isnan(el))

def remove_non_numerical(x, y): # it remove None and nan values but keeps strings for possible date or bar plots
   l = len(x)
   p = [i for i in range(l) if not (non_numerical(x[i]) or non_numerical(y[i]))]
   xn = [try_float(x[i]) for i in p]
   yn = [try_float(y[i]) for i in p]
   return xn, yn
```

any idea?

**Comment by Freed-Wu** [comment]
Take matplotlib as an example:
```python
import numpy as np
from matplotlib import pyplot as plt
a = np.arange(10.)
a[2:5] = [np.nan] * 3
plt.plot(a, "b")
plt.show()
```

is equal to

```python
import numpy as np
from matplotlib import pyplot as plt
a = np.arange(10.)
a[2:5] = [np.nan] * 3
plt.plot(range(0, 2), a[0:2], "b")
plt.plot(range(5, 10), a[5:10], "b")
plt.show()
```
![a](https://user-images.githubusercontent.com/32936898/187905996-5967756b-e753-4a55-911e-b6143e5fef6f.png)


So. I think just split the array to some parts by `np.nan`, and plot them
separately, which can solve this problem.

```python
import numpy as np
import plotext as plt
a = np.arange(10.)
a[2:5] = [np.nan] * 3
plt.plot(a)
plt.show()
```

**Comment by piccolomo** [comment]
Also if in your latest code you use scatter, the plot works

```
import numpy as np
import plotext as plt
a = np.arange(10.)
a[2:5] = [np.nan] * 3
plt.scatter(a)
plt.show()
```

![image](https://user-images.githubusercontent.com/56689657/187907686-769ee2dc-2463-4610-b3b4-9d94ec3c8a1b.png)

**Comment by Freed-Wu** [comment]
> It's a good idea, but I think it would still produce the same result as in your initial code / post.

```python
import numpy as np
import plotext as plt
a = np.arange(10.)
a[2:5] = [np.nan] * 3
plt.plot(range(0, 2), a[0:2], color="blue")
plt.plot(range(5, 10), a[5:10], color="blue")
plt.show()
```

![Screenshot from 2022-09-01 21-19-58](https://user-images.githubusercontent.com/32936898/187924002-daaf5481-c9da-4c08-b62d-3493ca0ce057.png)

1. a function to split the array to a list consisted of some arrays by `np.nan`
2. for each array in the list, plot them with the corresponding x coordinates.

**Comment by piccolomo** [comment]
If you let matplotlib deal with first code you sent, you get the same result as in plotext

**Comment by piccolomo** [comment]
Done! Somehow I managed!

![image](https://user-images.githubusercontent.com/56689657/187935433-d454c6bf-6d06-43ed-ad5c-75b6e6e2ccac.png)

It was not trivial but easier then I thought. I will upload the code soon

**Comment by piccolomo** [comment]
Interestingly this solves also the first issue you posted
![image](https://user-images.githubusercontent.com/56689657/187936000-1029f7e0-ed63-4cbe-9c0f-3ba772af28b0.png)

**Comment by Freed-Wu** [comment]
> It was not trivial but easier then I thought. I will upload the code soon

Great!

> matplotlib would not handle it the same way

Aha :smile:. I'll ask a problem to matplotlib about is it a bug or an expected behavior.

**Comment by piccolomo** [comment]
Cool thanks a lot for the report. The solution did not involve splitting data luckily (cause otherwise I would have to split all colors, style, and other parameters, which would have been a pain), but the matplotlib example you posted was useful for me to understand anyway. Basically I let nan or None "percolate" inside the calculation until its time to be drawn, where they are simply discared.

**Comment by Freed-Wu** [comment]
> The solution did not involve splitting data luckily (cause otherwise I would have to split all colors, style, and other parameters, which would have been a pain), but the matplotlib example you posted was useful for me to understand anyway. 

Great! :+1:

**Comment by Freed-Wu** [comment]
<https://github.com/matplotlib/matplotlib/issues/23797#issuecomment-1234416543>

>  I think we auto-scale based on valid points, if there is a nan in the y-value it is not a valid point so we are auto-scaling the x limits to show you the valid data.

It should be the expected behavior of matplotlib. Does plotext support auto-scale?

**Comment by piccolomo** [comment]
No, the new code will not update the x or y limits, it just lets the nan or None value show up to plotting time when they are discarded. The reason why the x limits are preserved at the end is because the x data has all regular values and its limits are calculated naturally.

> [matplotlib/matplotlib#23797 (comment)](https://github.com/matplotlib/matplotlib/issues/23797#issuecomment-1234416543)
> 
> > I think we auto-scale based on valid points, if there is a nan in the y-value it is not a valid point so we are auto-scaling the x limits to show you the valid data.
> 
> It should be the expected behavior of matplotlib. Does plotext support auto-scale?

**Comment by piccolomo** [comment]
Hi @Freed-Wu , I finally updated `plotext` including the changes you asked for. 

The new version is available [on GitHib](https://github.com/piccolomo/plotext) for now and soon also [on PyPi](https://pypi.org/project/plotext/). To install follow the indications [here](https://github.com/piccolomo/plotext#install).

Your changes are documented [here](https://github.com/piccolomo/plotext/blob/master/readme/notes.md#updates) and you have been credited [here](https://github.com/piccolomo/plotext/blob/master/readme/notes.md#credits).

Any feedback is welcomed.

Thanks a lot for your inputs and all the best,
Savino
