### ISSUE TITLE
Feature Request: Interactive Mode

### ISSUE THREAD

**Issue by Freed-Wu** [piccolomo/plotext#115]
Just like <https://github.com/olavolav/uniplot>?

Thanks.

**Comment by piccolomo** [comment]
Hi @Freed-Wu , I finally updated `plotext` including the changes you asked for. 

I introduced the function `interactive()`, but haven't tested properly so any feedback is welcomed. 

The new version is available [on GitHib](https://github.com/piccolomo/plotext) for now and soon also [on PyPi](https://pypi.org/project/plotext/). To install follow the indications [here](https://github.com/piccolomo/plotext#install).

Your changes are documented [here](https://github.com/piccolomo/plotext/blob/master/readme/utilities.md#useful-functions) and you have been credited [here](https://github.com/piccolomo/plotext/blob/master/readme/notes.md#credits).

Any feedback is welcomed.

Thanks a lot for your inputs and all the best,
Savino
