### ISSUE TITLE
Strange Coloring of Plot Right Borders

### ISSUE THREAD

**Issue by Freed-Wu** [piccolomo/plotext#116]
```python
import plotext as plt
y = plt.sin()
plt.plot(y)
plt.clc()
plt.show()
```

Actual:
![Screenshot from 2022-08-22 20-01-06](https://user-images.githubusercontent.com/32936898/185916484-6f80737d-37a8-4860-b296-8e772834991c.png)
![Screenshot from 2022-08-22 20-01-19](https://user-images.githubusercontent.com/32936898/185916500-071fe16c-5bdf-4cd9-bf79-fb4174ccc1bc.png)

Expected: right border should be white, not blue.
Thanks!

**Comment by piccolomo** [comment]
Thanks, will answer soon!

**Comment by piccolomo** [comment]
Hi @Freed-Wu , I finally updated `plotext` and the new version should solve this issue. 

The new version is available [on GitHib](https://github.com/piccolomo/plotext) for now and soon also [on PyPi](https://pypi.org/project/plotext/). To install follow the indications [here](https://github.com/piccolomo/plotext#install).

Any feedback is welcomed. Please report if the issue persists. 

Thanks a lot for your inputs and all the best,
Savino
