### ISSUE TITLE
Graph rendering and spaces between values

### ISSUE THREAD

**Issue by darul75** [piccolomo/plotext#119]
Hi,

Really like this lib, awesome work.

Would need some help on how to render this graph properly it currently result in this rendering with a lot a gap/spaces between values on y-axis.

![Screenshot 2022-08-29 at 12 17 18](https://user-images.githubusercontent.com/2134003/187179503-b2afe8dd-3987-477b-a309-e5a59d22b73a.png)

Any ideas on how to fix that.

I have tried using `plot` or `bar` graph type with no real success.

Data are a list of values by time.

`plt.bar(dates, values, color = 'red');`

**Comment by piccolomo** [comment]
I will come back to this, but for now quickly I would guess that it is a terminal problem. Are you in windows? Have you tried in Linux?

**Comment by piccolomo** [comment]
There was a similar issue reported, if I remember correctly.

**Comment by piccolomo** [comment]
I think it was [this one](https://github.com/piccolomo/plotext/issues/17).

**Comment by darul75** [comment]
Nice, that was it, thank you so much, learned something new again today.

**Comment by piccolomo** [comment]
Hi @darul75 , I finally updated `plotext` and I hope it solves the issue. 

The new version is available [on GitHib](https://github.com/piccolomo/plotext) for now and soon also [on PyPi](https://pypi.org/project/plotext/). To install follow the indications [here](https://github.com/piccolomo/plotext#install).

Any feedback is welcomed. Please report if the issue persists. 

Thanks a lot for your inputs and all the best,
Savino

**Comment by darul75** [comment]
Fantastic @piccolomo really like the result and the way you have been collaborating with me asking for a change. Great job! will let you know and test is asap.
