### ISSUE TITLE
Ability to add data series to a secondary axis.

### ISSUE THREAD

**Issue by Zaneo** [piccolomo/plotext#12]
Ability to add values to a secondary axis in the same plot.

```python
plt.scatter(x, y1, y-axis=0)
plt.scatter(x, y2, y-axis=1)
```

**Comment by piccolomo** [comment]
Dear Zaneo,

Thanks again for your comment and advise. I never thought about this idea and I will definitely think about it. If it will not be too tricky I will add it. 

I will update.
Cheers

**Comment by piccolomo** [comment]
Hi @Zaneo ,

the new version (3.0.0) of `plotext` is just available now at [this link](https://pypi.org/project/plotext/). 

Among the many changes, you can also independently [plot on both y axes](https://github.com/piccolomo/plotext#doubley) (the left and the right one).

Hope it help and thanks for help! 
Savino
