### ISSUE TITLE
plotext Not Working with watch package

### ISSUE THREAD

**Issue by wjfjfm** [piccolomo/plotext#120]
This is my tool using plotext: https://github.com/wjfjfm/sysbench_deviation

when I'm using "watch" to see the real time change, it output garbled like this:
![image](https://user-images.githubusercontent.com/24356422/187355360-c76c5459-6c23-47dd-a1a0-00c398999e61.png)

**Comment by piccolomo** [comment]
Hi @wjfjfm,

thanks for reporting. I have downloaded your files. What command do I run to try to recreate the error?

Thanks.

**Comment by wjfjfm** [comment]
@piccolomo Thank you and, after travel around "watch --help", I found that it doesn't support ANSI character by default. But it has a flag "-c or --color" to enable ANSI characters.

After using this flag, plotext work well with "watch.

Thanks for building this exellent tool :)

**Comment by piccolomo** [comment]
Hi @wjfjfm , I finally updated `plotext`. 

The new version is available [on GitHib](https://github.com/piccolomo/plotext) for now and soon also [on PyPi](https://pypi.org/project/plotext/). To install follow the indications [here](https://github.com/piccolomo/plotext#install).

Any feedback is welcomed. 

Thanks a lot for your inputs and all the best,
Savino
