### ISSUE TITLE
Feature request: Indicator Plot - KPI

### ISSUE THREAD

**Issue by darul75** [piccolomo/plotext#121]
hi,
is there a plan or a way to only display a KPI value with some text like in the following

-----
TITLE

36
----

Using subplot it would make a nice dashboard.

thank you

**Comment by piccolomo** [comment]
Hi @darul75,

thanks for dropping your input. I am not familiar with KPI. Would that mean something like a text + a value (integer or float)?
Or is it more like a plot of a sequence of values?

thanks

**Comment by darul75** [comment]
hi @piccolomo yeah very simple way to display some text 

here is an example, plenty on google https://www.klipfolio.com/resources/dashboard-examples/executive/kpi-dashboard

**Comment by piccolomo** [comment]
That is a cool idea. I was playing around with this code:

```
import plotext as plt
plt.clf()

y = [100 * (el / 2 + 0.5) for el in plt.sin(length=5000)]

def kpi(value, minimum = 0, maximum = 100, label = None):
    plt.bar([value], minimum = minimum, marker = 'sd', orientation = 'h')
    plt.xlim(minimum, maximum)
    plt.frame(0)
    plt.yfrequency(0)
    plt.xlabel(label)
    plt.plotsize(None, 7)
    plt.ticks_style('bold')

for el in y:
   plt.clt()
   plt.cld()
   kpi(el, 0, 100, "Sinusoidal")
   plt.show()
```

![Peek 2022-08-30 18-54](https://user-images.githubusercontent.com/56689657/187508783-2884edc5-7692-4bea-9d6f-a0d813ff4a96.gif)


Could that be a start? Or am I off?

thanks

**Comment by darul75** [comment]
My request is not very plot oriented indeed and would be just to be able to display a Key Performance Indicator into a sub block.

Like you got a graph on the left (bar/timeline/whatever plot graph) and on the right a KPI which is simply in general a Title and below a big Number, in screenshot above they do show a trend with an up/down arrow but this is not necessary.

**Comment by darul75** [comment]
Kpi could be Max and Min value.

Max
100

Min
17

**Comment by darul75** [comment]
But you got something else with this progress bar like chart :) an extra new feature.

**Comment by piccolomo** [comment]
Ye, here is another quick attempt: just text printed inside a plot, which could be easily inserted in a matrix of subplots

```
import plotext as plt
plt.clf()

y = [100 * (el / 2 + 0.5) for el in plt.sin(length=500)]

def kpi(value, label = None):
    plt.scatter([0, 1], marker = ' ')
    plt.yfrequency(0)
    plt.xfrequency(0)
    plt.clc()
    plt.frame(0)
    plt.text(label + ': ' + str(round(value, 1)), 1, 1, color = "red")

for el in y:
   plt.clt()
   plt.cld()
   kpi(el, "Label")
   plt.show()
   plt.time()
```

![Peek 2022-08-30 18-54](https://user-images.githubusercontent.com/56689657/187518247-ad12e61e-ce8f-49ea-91e7-96f3deb5af2b.gif)

**Comment by piccolomo** [comment]
frame(True) will make the plot more obvious

**Comment by darul75** [comment]
Nice, do you know if there would be a way to set some properties like Font size, colors...other than through global properties but just for that particular kpi element.

**Comment by darul75** [comment]
Just seeing color is available.

**Comment by darul75** [comment]
Also being able to align it or to place it at # pixel from top/left would be ideal.

Tested this
`plt.text('12', 1, 1, color = 'red', alignment = 'center'); \`

But label remains align on the left.

**Comment by piccolomo** [comment]
Ye, I am in the process of rewriting the code, and there would be a chance to add background color and style. I will update with something more detailed. 
In your previous code the alignment remains on the left because the text is on the left corner and so the alignment changes dynamically to remain inside the canvas. I will work on it. For now I wanted to know if this is the direction you were envisioning.

**Comment by darul75** [comment]
Does not have to be perfect but yes you got it, here is one good example, then we are in a terminal so it does not have to be so pretty. https://user-images.githubusercontent.com/2134003/187484359-3816e746-221f-4de6-88ba-f2fdc952fd0d.png

**Comment by piccolomo** [comment]
Hello, 
what do you think about something like this?

![image](https://user-images.githubusercontent.com/56689657/187904408-b30b2af2-ca6a-4645-93f0-46203b557605.png)

**Comment by darul75** [comment]
honestly having just the number label centered vertically/horizontally in the middle of the box and for which we can define a font size would be perfect, the arrow "trend" not being necessary.

**Comment by piccolomo** [comment]
cool, font size is fixed by terminal and cannot do anything about it, for now.

**Comment by darul75** [comment]
getting it centered in that case would be awesome

**Comment by piccolomo** [comment]
great, the trend element will be optional

**Comment by piccolomo** [comment]
Hi @darul75 , I finally updated `plotext` including the changes you asked for. 

I introduced the function `indicator()`, but haven't tested properly so any feedback is welcomed. 

The new version is available [on GitHib](https://github.com/piccolomo/plotext) for now and soon also [on PyPi](https://pypi.org/project/plotext/). To install follow the indications [here](https://github.com/piccolomo/plotext#install).

Your changes are documented [here](https://github.com/piccolomo/plotext/blob/master/readme/other.md#indicator) and you have been credited [here](https://github.com/piccolomo/plotext/blob/master/readme/notes.md#credits).

Any feedback is welcomed.

Thanks a lot for your inputs and all the best,
Savino

**Comment by darul75** [comment]
put my comment in the wrong ticket but for sure you saw it. looking great will give it a try next week

**Comment by piccolomo** [comment]
@darul75 , no problem been correcting small typos in my code for days... so ye i understand! thanks for appreciation.

**Comment by piccolomo** [comment]
Hello @darul75,

  [plotext 6](https://plotext.readthedocs.io/en/latest/) is out, and it has no `indicator()` method: the same box is built from the methods already there, so nothing is lost and the look is yours to change.

  ```python
  import plotext as plt
  fig = plt.figure
  fig.clear()
  fig.plot_size(30, 8)

  value, label, trend = 123, "Active Users", +5

  parts = plt.colorize(str(value), pixel = ('orange+', None, 'bold'))
  if trend is not None:
      arrow       = '↑' if trend > 0 else '↓' if trend < 0 else '↔'
      arrow_color = 'green' if trend > 0 else 'red' if trend < 0 else 'orange'
      parts = parts.hstack(plt.colorize(' ' + arrow, pixel = (arrow_color, None, 'bold')))

  fig.ruler('x').frequency(0); fig.ruler('y').frequency(0)   # no ticks, the frame alone
  fig.ruler('x').lim(0, 1); fig.ruler('y').lim(0, 1)
  fig.title(label)
  fig.draw(fig.text(0.5, 0.5, parts, alignment = 'center'))
  fig.show()
  ```
  which gives:
![indicator](https://raw.githubusercontent.com/piccolomo/plotext/master/docs/source/images/indicator.png)

Several indicators side by side is a matter of putting each in its own [subplot](https://plotext.readthedocs.io/en/latest/subplot.html). The recipe is documented in the [indicator](https://plotext.readthedocs.io/en/latest/specialized.html#indicator) section of the guide, and I have added you to the [credits](https://plotext.readthedocs.io/en/latest/credits.html) for asking for it.

  - the [repository](https://github.com/piccolomo/plotext) on GitHub
  - the [package](https://pypi.org/project/plotext/6.0.0/) on PyPI, installed with `pip install plotext --upgrade`
  - the [guide](https://plotext.readthedocs.io/en/latest/) on Read the Docs

Thank you for the request, and for your patience.
Savino
