### ISSUE TITLE
Syntax Error Using Python3.7 

### ISSUE THREAD

**Issue by S1SYPHOS** [piccolomo/plotext#124]
Hey there,
on Python v3.7, I get this when importing `plotext`:

```text
_utility.py", line 554
E       return xl, yl, *transpose(ol, len(other))
E                      ^
E   SyntaxError: invalid syntax
```

Seems like a regression, but I'm not familiar with your code :confused: 

Cheers,
S1SYPHOS

PS: I just love this library, so flexible, much wow!

**Comment by piccolomo** [comment]
oh thanks for the report and appreciation! 😀

btw i guess that should not be a syntactical problem. maybe your python version is  old? i am using 3.10. about you?

**Comment by piccolomo** [comment]
oh you wrote python version. i will investigate and report

**Comment by S1SYPHOS** [comment]
Yeah, 3.7 - 3.10 runs through my testing pipeline, all others were alright, but 3.7 failed :disappointed:

**Comment by piccolomo** [comment]
Hi @S1SYPHOS,
I changed the github version to solve this issue, but I cannot fully test it on my machine, as I cannot find a quick way to install packages only on python3.7. Could you kindly install and check that version 5.2.3 (on githib only for now) works well in Python3.7, by using test() for example.

Thanks

**Comment by S1SYPHOS** [comment]
sec ..

**Comment by S1SYPHOS** [comment]
seems fine! error's gone

**Comment by piccolomo** [comment]
:+1: :-) Great thanks! I shall upload it on PyPi soon, but I will wait a few days, as few other little mistakes may appear. 
If you find other bugs, welcomed! 
Thanks!

**Comment by piccolomo** [comment]
I link here similar [issue](https://github.com/piccolomo/plotext/issues/130), now solved.
