### ISSUE TITLE
How To: Build Date Time Plot by Hour of Days

### ISSUE THREAD

**Issue by darul75** [piccolomo/plotext#128]
Hello,

I would like drawing a scatter plot with a count on the y axis and each hours of the day on the x axis.

Is it possible?

Thanks in advance.

**Comment by piccolomo** [comment]
Hi @darul75,

thanks for posting. Here is an example of code with result:

![image](https://user-images.githubusercontent.com/56689657/189609828-fc3982f7-c39c-43c0-924d-4b571675cba2.png)

Basically the trick is in using plt.date_form('H') as explained [here](https://github.com/piccolomo/plotext/blob/master/readme/datetime.md#utilities).

**Comment by piccolomo** [comment]
Btw, if that part of the guide is difficult to understand, please leave some feedback so that I could make it clearer. I would understand, any feedback is appreciated.

**Comment by piccolomo** [comment]
P.s. little mistake: if you need a scatter plot instead, you could use the function `scatter()`.

**Comment by darul75** [comment]
thank you, great, was not sure the `scatter` function could be used in the same way as your example in the documentation exposes a sin() function but not with some real data values.

**Comment by piccolomo** [comment]
Glad it helped! :+1:
