### ISSUE TITLE
Ability to have multiple plots on the same console.

### ISSUE THREAD

**Issue by Zaneo** [piccolomo/plotext#13]
If secondary axis is too difficult, would it be possible to have subplots, or multiple plots to display data?

**Comment by piccolomo** [comment]
Dear Zaneo,

Thanks for your comment and advise. I was thinking as well to add the subplots feature to plotext but I will work on it after the histogram and logplot features, also because it requires some fondamental changes to the code.

I will update.
Cheers

**Comment by piccolomo** [comment]
Hi @Zaneo ,

the newest version (3.0.0) of `plotext` is now available at [this link](https://pypi.org/project/plotext/).

Among the many changes, there is the possibility of plotting [multiple plots](https://github.com/piccolomo/plotext#subplots) in a grid.

Hope it help and thanks for help! 
Savino
