### ISSUE TITLE
Python3.7 not working with Plotext 5.2 

### ISSUE THREAD

**Issue by lewoudar** [piccolomo/plotext#130]
Hello, I was trying your library and on the first attempt I got this message:

```python
Traceback (most recent call last):
  File "test.py", line 1, in <module>
    import plotext as plt
  File "/home/kevin/Documents/plot/venv/lib/python3.7/site-packages/plotext/__init__.py", line 6, in <module>
    from ._core import *
  File "/home/kevin/Documents/plot/venv/lib/python3.7/site-packages/plotext/_core.py", line 10, in <module>
    from plotext._figure import _figure_class
  File "/home/kevin/Documents/plot/venv/lib/python3.7/site-packages/plotext/_figure.py", line 1, in <module>
    from plotext._default import default_figure_class
  File "/home/kevin/Documents/plot/venv/lib/python3.7/site-packages/plotext/_default.py", line 2, in <module>
    from plotext._utility import no_color
  File "/home/kevin/Documents/plot/venv/lib/python3.7/site-packages/plotext/_utility.py", line 554
    return xl, yl, *transpose(ol, len(other))
                   ^
SyntaxError: invalid syntax
```

I try the first example in the documentation:

```python
import plotext as plt
y = plt.sin() # sinusoidal signal
plt.scatter(y)
plt.title("Scatter Plot")
plt.show()
```
My environment:
- OS: Ubuntu
- Python version 3.7.7

**Comment by piccolomo** [comment]
Hi @lewoudar,

thanks for posting. This issue is similar to [this one](https://github.com/piccolomo/plotext/issues/124) and solved in GitHub version. 

I will delete this duplicate, when I will upload to PyPi, if you are ok with it. I hope this helps.

Thanks, 
Savino

**Comment by lewoudar** [comment]
Hum.. I still have the same issue with the latest version :/

**Comment by piccolomo** [comment]
Hi @lewoudar , thanks. Somehow I modified the `_utility.py` file before to solve that error before,. 

Anyway, I now have modified the file again to solve the issue. Could you kindly test it again?

Thanks a lot !

**Comment by lewoudar** [comment]
I have another error now (dependency conflict):

```python
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/kevin/Documents/plot/venv/lib/python3.7/site-packages/plotext/__init__.py", line 7, in <module>
    from .plotext_cli import build_parser
  File "/home/kevin/Documents/plot/venv/lib/python3.7/site-packages/plotext/plotext_cli.py", line 5, in <module>
    import shtab
ModuleNotFoundError: No module named 'shtab'
```

Little advice: I checked your project quickly and it seems that you didn't write unit tests. It is good practice to write them, it will help you catch many errors before users tell you. After writing the tests, you probably want to set up a CI using something like [GitHub Actions](https://docs.github.com/en/actions) and check your project against different environments (Windows, Mac OS, Linux) 
Hope this will help you 🙂

**Comment by piccolomo** [comment]
Hi @lewoudar, thanks for feedback and advices! I am will work on `plotext `soon to fix this error as well. In the meantime you could try to install `shtab`, to temporarily fix the issue.

**Comment by piccolomo** [comment]
Hi @lewoudar , I finally updated `plotext` including the changes you asked for. 

The new version is available [on GitHib](https://github.com/piccolomo/plotext) for now and soon also [on PyPi](https://pypi.org/project/plotext/). To install follow the indications [here](https://github.com/piccolomo/plotext#install).

Any feedback is welcomed. I have not double test it on Python3.7. I close but if issue persists, please keep updated.

Thanks a lot for your inputs and all the best,
Savino

**Comment by piccolomo** [comment]
P.S thank you for your advice regarding unit testing, which I will work on later on.

**Comment by lewoudar** [comment]
Hi @piccolomo, it now works when installing it from git source. It just remains to add it on pypi. Thanks

**Comment by piccolomo** [comment]
[PyPi](https://pypi.org/project/plotext/) version updated: thanks for reminding.

**Comment by lewoudar** [comment]
You are welcome :)
