### ISSUE TITLE
Custom colors on stack_bar chart

### ISSUE THREAD

**Issue by darul75** [piccolomo/plotext#131]
Hello,

Would it be possible to set custom colors (2 colors) on stack_bar charts other than the defaults:

Example code truncated:

```
plt.subplot(2, 2); \
plt.stacked_bar(....); \
```
giving

![Screenshot 2022-09-19 at 11 26 04](https://user-images.githubusercontent.com/2134003/191027606-fae89e07-c80f-4753-8200-71f06cd49712.png)

```
plt.clc(); \
plt.subplot(2, 2); \
plt.stacked_bar(....); \
```

giving

![Screenshot 2022-09-19 at 11 25 54](https://user-images.githubusercontent.com/2134003/191027951-9af61fd7-ec6f-4e65-a7c5-cc0a4eb3fba8.png)

Also, is there another way to avoid this **grey** background on any charts so it takes the default current terminal background?

To avoid it I used `plt.clc()` everywhere.

![Screenshot 2022-09-19 at 15 28 06](https://user-images.githubusercontent.com/2134003/191028364-84fae4ee-f9e2-45b3-b521-c94ac4b847da.png)

**Comment by darul75** [comment]
Oh I see, checked your code and I can pass an array

`, color = ['black', 'blue']`

**Comment by piccolomo** [comment]
No problem, I am out of plotext for awhile and will be back.

**Comment by darul75** [comment]
before going away :) can you tell me how I can retrieve the size (height/width) of the current figure or plot..I would need that to do something dynamically. have tried different things but cant get these values. in pixel or rows columns whatever. thx

**Comment by piccolomo** [comment]
ok, i may add this function in the future, but for now: ù
try plt.figure._size for overall figure,
and plt.figure._get_subplot(1,1)._size for a subplot if it exists.

- Savino

**Comment by piccolomo** [comment]
This could be a feauture request, if you find it usefull. Feel free to open.
