### ISSUE TITLE
Ticks without decimals (question)

### ISSUE THREAD

**Issue by darul75** [piccolomo/plotext#136]
Hello @piccolomo 

Is there a way to display tick labels without unnecessary decimal values.

<img width="39" alt="Screenshot 2022-10-03 at 13 35 11" src="https://user-images.githubusercontent.com/2134003/193567881-3f645433-2f71-4f84-8f14-31cb3b2da995.png">

Where here I would prefer seeing 1 instead of 1.0 etc.

Thank you,
Julien

**Comment by piccolomo** [comment]
Using the function `yticks(ticks, labels)` (explained in section Settings > Plot Ticks). Labels could be pure integers converted to string.

**Comment by darul75** [comment]
Read it but not carefully enough.

**Comment by darul75** [comment]
Managed to do it for `bar` type chart but can not work out how to do the same for a `stacked_bar` chart where I got similar values on one axis (y axis).

**Comment by piccolomo** [comment]
Hi, I have solved this issue in the GitHub version tagged 5.2.8 (not yet published on PyPi). I tested it and it seem to work with axes ticks which are all integers, but if you could double check, I would be grateful. To install: `pip install git+https://github.com/piccolomo/plotext`.
Thanks for reporting!

**Comment by darul75** [comment]
hey, nice will test it soon and let you know

**Comment by piccolomo** [comment]
no problem, thank you anyway
