### ISSUE TITLE
Text background and color does not work together

### ISSUE THREAD

**Issue by ineteye** [piccolomo/plotext#141]
Hi!

Text background and color does not work together

```
import yfinance as yf
import plotext as plt

plt.date_form('d/m/Y')
start = plt.string_to_datetime('11/06/2022')
end = plt.string_to_datetime('10/10/2022')
data = yf.download('goog', start, end)
dates = plt.datetimes_to_string(data.index)
plt.xlim("10/06/2022", "15/10/2022")
plt.candlestick(dates, data, yside = 2)
plt.hline(100,'red',yside=2)
# If NO  - background='red'  - color black applys.
plt.text(' 100 ',x='12/10/2022',y=100,background='red',color='black',yside=2)
plt.show()
```

![image](https://user-images.githubusercontent.com/32996306/194777012-b8a2dbdc-6bea-40d3-b8f2-607e9b2e3c32.png)

If i remove background='red' : 

![image](https://user-images.githubusercontent.com/32996306/194777365-070ba715-4fc4-484d-a1b2-5ec0818e6b4d.png)

**Comment by piccolomo** [comment]
Hi @ineteye,

thanks for the report, but I do not follow, as it seems then in both cases in gives the intended result. Am I missing something?
First Case: black on red (I get black on red)
Second Case: black (I get black with automatic canvas background)

**Comment by piccolomo** [comment]
This may be a terminal related issue, cause all works fine on me: what operating system and terminal are you using, if I could ask?

**Comment by ineteye** [comment]
Thats strange i have this on windows:
![image](https://user-images.githubusercontent.com/32996306/194778984-d4fcb33e-f791-4799-af8a-89bae3555041.png)

**Comment by ineteye** [comment]
And this on Ubuntu 22.04

![image](https://user-images.githubusercontent.com/32996306/194779018-f5a18607-dc0f-4125-bf30-3fd10a0729ec.png)

**Comment by piccolomo** [comment]
Strange, I am on Ubuntu 22 and I see what you see on Windows. Are you sure you are not mixing the two?

**Comment by ineteye** [comment]
Found problem :)) it in Vscode only ... Same code in Visual Studio Code and Ubuntu Terminal

![image](https://user-images.githubusercontent.com/32996306/194779148-e8ade478-24f2-42a3-b667-dcf42879ab83.png)

**Comment by piccolomo** [comment]
So I understand that all is good on Ubuntu, on your side?

**Comment by ineteye** [comment]
On Ubuntu Terminal and Windows Terminal, but not in Visual Studio Code... It draw on white, so problem.

**Comment by piccolomo** [comment]
got it. Not sure how to help then. If you find a solution, keep reporting please, it may help someone else. 

Thanks for reporting

**Comment by piccolomo** [comment]
P.S. if you want to play around coloring in Visual Studio Code, try directly the `colorize()` function with different colors and backgrounds. Guide [here](https://github.com/piccolomo/plotext/blob/master/readme/utilities.md#colored-text). Thanks

**Comment by ineteye** [comment]
Ok i will try ;)) If will be successful will post here ;)

**Comment by ineteye** [comment]
Tried colorize and looks same result...
So its just does not work in VsCode

![image](https://user-images.githubusercontent.com/32996306/194780613-be490f41-4f0f-4895-b3d3-8e66dd381eae.png)

**Comment by ineteye** [comment]
Also is it possible to set the color and type(dot-like) of the grid?
I checked your docs and did not find any mention of that.

**Comment by piccolomo** [comment]
Ye! I guess those little embedded terminal are not idea. 

Regarding grid color: you could use the `ticks_color()` function. But the type cannot be changed, only the color.

**Comment by piccolomo** [comment]
Guide [here](https://github.com/piccolomo/plotext/blob/master/readme/aspect.md#colors).

**Comment by piccolomo** [comment]
I guess if you want horizontal or vertical dot lines, you could create them artificially with the `plot()` function. 
![image](https://user-images.githubusercontent.com/56689657/194780933-f10e42b6-9963-4f71-bfdf-31cd58a7a650.png)

**Comment by ineteye** [comment]
no i was thinking about plt.grid(x=30,y=30) cause it synced with ticked
Something like that:
![image](https://user-images.githubusercontent.com/32996306/194781275-252d8aa7-c6e2-4775-b0c0-b5811f5cf375.png)

**Comment by ineteye** [comment]
By the way is it possible to make 3 subplots not 4?
It one of most useful view for stocks ;)

Something like that, when you have 1 row on first column
and 2 rows and second column
![image](https://user-images.githubusercontent.com/32996306/194782121-63c70f22-2dc7-4481-82ca-bbf5dc0e0f7c.png)

**Comment by piccolomo** [comment]
Here it is! This also shows how to dim the grid line color.

![image](https://user-images.githubusercontent.com/56689657/194782427-7c57fca0-5b05-4e80-817b-4ba6d912aa01.png)

**Comment by piccolomo** [comment]
Or: 
![image](https://user-images.githubusercontent.com/56689657/194782491-9dd65cb4-a4fa-4393-9429-cd349ccc1879.png)

**Comment by ineteye** [comment]
Thanks!! Eve-some ;)))

**Comment by piccolomo** [comment]
Hi, I have deleted some posts not directly connected to initial issue, for clarity. Any other report is quite welcomed, in new issue.
