### ISSUE TITLE
Feature Request: Remove Side Symbols in Legend (like ⅃) for Single Data Set

### ISSUE THREAD

**Issue by ineteye** [piccolomo/plotext#142]
Hi!

Have this symbol on plot before label: ⅃
Looks it should not print, i did not saw it on screens

```
import yfinance as yf
import plotext as plt

plt.date_form('d/m/Y')
start = plt.string_to_datetime('11/06/2022')
end = plt.string_to_datetime('10/10/2022')
data = yf.download('goog', start, end)
# data.reset_index(drop=True)
dates = plt.datetimes_to_string(data.index)
plt.xlim("10/06/2022", "15/10/2022")
plt.candlestick(dates, data,label='GOOG',yside = 2)
plt.hline(100,'red',yside=2)
plt.text(' 100 ',x='12/10/2022',y=100,background='red',color='black',yside=2)
plt.show()
```

![image](https://user-images.githubusercontent.com/32996306/194904859-272c3882-d92c-4ffc-bf91-351d7b3715a6.png)

**Comment by piccolomo** [comment]
Hello @ineteye , thanks for reporting.

This an intended feature. When your axes are not the standard one (left y, lower x), it shows an icon that tells you where you are plotting. 

Thinking out loud: Probably useless when you are plotting just on one set of data (more useful when multiple data are shown on different axes), and may find a way around this and update.

**Comment by ineteye** [comment]
So its not possible to hide right now? Ok i will wait for update, THanks ;)))

**Comment by piccolomo** [comment]
No, unless you revert to normal axes plot. I will update neverthless

**Comment by ineteye** [comment]
Thanks ;))

**Comment by piccolomo** [comment]
About this:

```python
import plotext as plt; 
plt.clf(); 
plt.subplots(2,1); plt.subplot(1,1).plotsize(None, 4); 
plt.subplots(1,2).frame(1); plt.subplot(1,1).subplot(1,1).indicator(10,"High", color="green");
plt.subplot(1,1).subplot(1,2).indicator(5,"Low", color = "red");
 plt.subplot(2,1).plot(plt.sin()); 
plt.show()
```

![image](https://user-images.githubusercontent.com/56689657/194967248-fc20bf3c-9f00-45c1-a05b-f764ee899bbd.png)

**Comment by piccolomo** [comment]
Hi @ineteye,

issue solved in new github version. 

Now this code: import plotext as plt; plt.clf(); plt.plot([1,2], yside=2, label="some label"); plt.show()
outputs 
![image](https://user-images.githubusercontent.com/56689657/198111265-3c5bb327-8e77-44bd-a668-91ca36daec6a.png)
while this, normally outputs:
![image](https://user-images.githubusercontent.com/56689657/198111401-93a93def-7a90-4b53-9c7e-f11ba964e948.png)

Thanks for reporting! :-) Does it help?
