### ISSUE TITLE
Feature Request: Heatmap Plot

### ISSUE THREAD

**Issue by joelostblom** [piccolomo/plotext#143]
I think it would be cool and useful to make heatmaps in the terminal. I don't know if there are enough colors to use that as a meaningful value mapping, but maybe different sizes of unicode square and circles could be helpful to use sizes instead of / in addition to color. I am thinking something similar to github punchcards, so simpler than the current options for plotting images and more in line with the design for the simple bar plots.

I think this design is pretty close to what I am thinking (from https://mkaz.blog/misc/terminal-heatmap-chart/ and https://github.com/mkaz/termgraph):

![image](https://user-images.githubusercontent.com/4560057/194927487-5b88423c-8cd0-4ea8-9a48-aa5b63ff6327.png)

Some more images for inspiration:

![image](https://user-images.githubusercontent.com/4560057/194926844-48bb950b-c20a-4f6c-9584-ed4f90b6a711.png)

![image](https://user-images.githubusercontent.com/4560057/194926585-289ea963-f9f7-4b38-b9e1-d317d5771b3b.png)

Related project https://github.com/jclulow/terminal-heatmap

**Comment by piccolomo** [comment]
Cool idea, will investing it!

**Comment by Jepson2k** [comment]
This would be super useful!

**Comment by piccolomo** [comment]
i agree, i am kind of hibernatiom mode now in terms of coding for plotext (not in general hopefully). would come back to it.

any specific coding idea about it is welcomed

**Comment by Jepson2k** [comment]
No worries, I plan on using this library to plot heatmaps in a textual (textualize) tui application. So I might make something similar to the current confusion matrix feature sometime in the next few months. If I do I'll post some code or open a pr.

**Comment by piccolomo** [comment]
Hi @joelostblom,

sorry for being so late: I have been quite busy. 

Are you still available for this? Any idea you worked on in the meanwhile?

Thanks, Savino

**Comment by joelostblom** [comment]
No worries, I know what it's like to get busy. I'm stil interesting in having this feature and think it could be really helpful. However I'm not in a space to be able to contribute code at the moment but I'm happy to discuss potential implementations.

**Comment by GNtrazios** [comment]
Hi @joelostblom, @piccolomo. I would like to give a try in this feature request. Is it still available and if yes, could you give me some guidelines or any progress so far?
Thank you

**Comment by piccolomo** [comment]
@GNtrazios , you would be very welcomed. At the moment I am re-writing the code for next version, so hopefully your changes could be reapplied smoothly, but it should not be a problem as I think most of the work would be done using the matrix plot utility
function ([here](https://github.com/piccolomo/plotext/blob/master/readme/special.md#matrix-plot)).

**Comment by GNtrazios** [comment]
Perfect! I am working on it.

**Comment by GNtrazios** [comment]
I have some progress on that but I want to specify what is the expected input of the heatmap

**Comment by piccolomo** [comment]
> I have some progress on that but I want to specify what is the expected input of the heatmap

@GNtrazios my guess is as good as yours for now, perhaps @joelostblom knows more already.

**Comment by joelostblom** [comment]
Thanks for working on this @GNtrazios ! I think long form data would make sense for the input, rather than wide form. Wide form can make sense for heatmaps as well, so if it is much easier for you to implement you can go with that and people will have to reshape their data manually.

For an example of what long form data would look like, you can see this snippet in Altair https://altair-viz.github.io/gallery/table_bubble_plot_github.html

![image](https://github.com/piccolomo/plotext/assets/4560057/d9a0b21f-3d03-424e-a9ce-45cf0fe3a381)

**Comment by GNtrazios** [comment]
I have a question about how to see the result of my progress so far. I make changes in pycharm and i want to run the code.

**Comment by joelostblom** [comment]
You can make an editable install of plotext via `pip install -e plotext`; then any changes you make will take effect once you restart the python kernel. Ideally you would fork the repo and clone it to your computer first; navigate to the folder and run  `pip install -e .`
