### ISSUE TITLE
Date Time Plot Y Limits

### ISSUE THREAD

**Issue by ineteye** [piccolomo/plotext#146]
Hi!

Played today with ylim

I add this line,to limit Y axis
plt.ylim(50.00,100.00)
but no changes
Am I doing something wrong?

```
import yfinance as yf
import plotext as plt
plt.clf()
plt.date_form('d/m/Y')
start = plt.string_to_datetime('11/04/2022')
end = plt.today_datetime()
data = yf.download('goog', start, end)
dates = plt.datetimes_to_string(data.index)
plt.xlim("01/04/2022", "15/10/2022")
plt.ylim(50.00,100.00)
plt.candlestick(dates, data, yside = 2) # or yside = "right"
plt.show()
```

![image](https://user-images.githubusercontent.com/32996306/195374390-fd64686a-b053-4d0d-9a7d-eaf33e8cdff7.png)

**Comment by piccolomo** [comment]
try ylim with option yside = 2

**Comment by ineteye** [comment]
Thanks! That helps!

**Comment by piccolomo** [comment]
no problem, glad it helps. for little issues like these you could write me directly by email, without opening issue.

**Comment by piccolomo** [comment]
I close this one, as it seems solved. Thanks for reporting! :-)
