### ISSUE TITLE
limit dimensions to r x c chars

### ISSUE THREAD

**Issue by dparvaz** [piccolomo/plotext#147]
I'm sorry if I missed this in the docs, but is there a way to not have the graph take up entire terminal width? I'm thinking about having multiple graphs/charts on the same screen.

Many thanks,

-Dan.

**Comment by piccolomo** [comment]
Hi, thanks for the question. Here are two functions to begin with:

- `plot_size(width, height)` explained [here](https://github.com/piccolomo/plotext/blob/master/readme/settings.md#plot-size),
- `subplots(rows, cols)` explained [here](https://github.com/piccolomo/plotext/blob/master/readme/subplots.md#subplots).

Let me know, if you need more help.
All the best, 
Savino

**Comment by dparvaz** [comment]
Just what the doctor ordered! Many thanks.
