### ISSUE TITLE
Float formatting inconsistent

### ISSUE THREAD

**Issue by jayhale** [piccolomo/plotext#159]
The formatting of float values is inconsistent - e.g.:

<img width="796" alt="image" src="https://user-images.githubusercontent.com/31579448/210149015-e58c9068-9b59-4c22-bd65-21437ebe4ef4.png">

**Comment by piccolomo** [comment]
Hi @jayhale ,

thanks for the report. I will work on it. 

I won't be working on `plotext  for a few weeks, tough.

Savino

**Comment by jayhale** [comment]
@piccolomo thanks. If you point me to the right place in the source, I'd be happy to PR.

**Comment by piccolomo** [comment]
Hi @jayhale,

[here ](https://github.com/piccolomo/plotext/blob/ef858ab454e3b99cdbf4d2f4848026b6cbfef78d/plotext/_global.py#L17)

there are also related functions in the _utility.py file. 

Just to warn: there is another issue related to extending the functionalities to negative bars.

**Comment by madnight** [comment]
I have the same problem. I think it would be nice to allow a chart parameter to specify number of decimals of float, like so `f"{row_value:.{precision}f}"`

**Comment by piccolomo** [comment]
Got it. As soon as I get back to coding for `plotext`, I will surely deal with it! Thanks for commenting !

**Comment by piccolomo** [comment]
I closed this one, as I merged [the corresponded PL](https://github.com/piccolomo/plotext/pull/163)! 

Thanks a lot for the report! and sorry for late reply! 

Savino :-)
