### ISSUE TITLE
Horizontal bar chart support

### ISSUE THREAD

**Issue by robintw** [piccolomo/plotext#16]
This library looks great, and I'm starting to use it in my project.

As well as doing line plots, I was hoping to do horizontal bar charts that look a bit like the following (although ideally with axis ticks and so on as well):

```
Foo  #########
Bar  ####
Baz  ###########
```

I was hoping this would be a fairly simple modification of the existing `hist` command (as this is basically a simplified version of a histogram), but it looks like it's more complicated than that, as we need separate labels for each of the categories. I've also had an issue running the `hist` example code (see #15).

Also, is the code available fully in the Github repository? When I clone the repository, the `plotext` folder seems to be a submodule, but I can't seem to retrieve the contents of the submodule. Could you let me know what git commands I need to run to get hold of the full code? (At the moment, I'm browsing the code in the folder that pip installed it to, which is not ideal). I've got a small PR I'd like to submit, but I can't work out how to submit it if I can't get full access to the code in Git.

**Comment by piccolomo** [comment]
Hi robintw,

the bar chart is coming in the next version.... soon... :-) 

Also thanks for reporting the problem with downloading the GitHub code. I just checked and there was a hidden .git folder in the plotext directory which probably was instructing GitHub not to show the content of the folder. I deleted it and all went well. Sorry I am not that familiar with GitHub or project creation with Python either, I must have copied and pasted from template projects online or something to that effect.

All the best and I will update regarding the bar plot.

**Comment by Sauci** [comment]
@piccolomo any news on this? I modified my local version to add the feature, but if it is already done in your local version, I wont create a pull request... Thank you in advance for your feedback

**Comment by piccolomo** [comment]
Hi @Sauci 

thanks for your code, which I will definitively look into and possibly integrate in the next version. I am currently very busy applying many other due changes, like subplots, log scale, double axis, date time support and others and it is going to take some time to arrive at next version, but i will definitely look at the code in more details and come back at you. 

For now thanks and I will keep updated. Thanks for help!

**Comment by piccolomo** [comment]
Hi @Sauci ,

**Comment by piccolomo** [comment]
Hi @Sauci,

the new version (3.0.0) of `plotext` is just available now at [this link](https://pypi.org/project/plotext/). Among the many changes, the [bar plot ](https://github.com/piccolomo/plotext#bar-plot) is now available. 

Hope it help and thanks for help! 
Savino
