### ISSUE TITLE
Colorless Docstrings 

### ISSUE THREAD

**Issue by Freed-Wu** [piccolomo/plotext#161]
See <https://github.com/prompt-toolkit/ptpython/issues/505>.

**Comment by piccolomo** [comment]
Thank you @Freed-Wu !

**Comment by piccolomo** [comment]
Hi @Freed-Wu,

Sorry for such long break. 

The new version (only on GitHub for now) has also docstrings free from ansi codes. 

The docstrings are explained [here](https://github.com/piccolomo/plotext/blob/master/readme/utilities.md#docstrings) and the installing instructions are [here](https://github.com/piccolomo/plotext/blob/master/readme/notes.md#install).

All the best,
Savino
