### ISSUE TITLE
Inconsistent themes across terminals.

### ISSUE THREAD

**Issue by thisismygitrepo** [piccolomo/plotext#168]
I'm simply running `plt.clf(); plt.plot([1, 2, 4]); plt.show()`
and it shows a plot with white background on linux machine and black background on windows machine.
In both instances I'm running the command in interactive ipython shell.

Additionally, I could not find anywhere in the docs where to change the theme. Only one of the examples of bar plots seems to be with dark background with no explanation.

Thank you.

**Comment by thisismygitrepo** [comment]
I found one place where `theme` is mentioned explicitly, [enviroments](https://github.com/piccolomo/plotext/blob/master/readme/environments.md) but I'm not able to explain the difference in behaviour across terminals.

**Comment by thisismygitrepo** [comment]
With further investigation, turns out that what I saw on Windows was not a `dark` theme, it actually black and white. Colors seems to be missing on windows machine.

![image](https://user-images.githubusercontent.com/46288868/230802259-455deae3-20aa-4e3c-ad5a-8087939e32c7.png)

**Comment by piccolomo** [comment]
Hi, glad you found a solution. 

Anyway themes are explained [here](https://github.com/piccolomo/plotext/blob/master/readme/aspect.md#themes).

All the best,
Savino

**Comment by piccolomo** [comment]
Hi @thisismygitrepo, and sorry for the very late word on this.

  You were right that something was off: the plot came out black and white on your Windows machine while the same code was colored on Linux, which is not a theme matter at all, only whether the terminal is showing the colors.

  Version 6 of [plotext](https://plotext.readthedocs.io/en/latest/) was tested on Windows this week, in `cmd` as well as Windows Terminal, and the plots come out **colored**, with the twelve themes rendering as they do elsewhere. Two smaller differences on that system: the `hd` and `braille` markers draw
  properly, while `fhd` is not available there, its characters asking for more room than a Windows character has.

  ```python
  import plotext as plt

  fig = plt.figure
  fig.theme("matrix")
  fig.draw(fig.signal(plt.sin()).lines())
  fig.title("a theme on Windows")
  fig.show()
  ```

  Every theme, and how to write your own, is on the [theme](https://plotext.readthedocs.io/en/latest/theme.html) page; `plotext.themes()` prints them all side by side.

  plotext 6 is out as a beta:

  - GitHub: https://github.com/piccolomo/plotext
  - PyPI: https://pypi.org/project/plotext/6.0.0b0/, installed with `pip install --pre plotext`
  - documentation: https://plotext.readthedocs.io/en/latest/

  Thanks for reporting it,

  Regards,
  Savino
