### ISSUE TITLE
histogram rendering looks weird

### ISSUE THREAD

**Issue by marcomusy** [piccolomo/plotext#17]
This looks a very cool library! While testing histogramming I get this output from the example script
(on my mac terminal)
<img width="416" alt="Screenshot 2021-03-28 at 23 59 35" src="https://user-images.githubusercontent.com/32848391/112769551-fe516600-9021-11eb-8b8d-2f60a641b324.png">

<img width="275" alt="Screenshot 2021-03-29 at 00 03 51" src="https://user-images.githubusercontent.com/32848391/112769602-42dd0180-9022-11eb-9b7d-f8b41e4631d4.png">

any ideas of why is that?

I ask because some time ago I implemented something similar for `vedo` and it has the same problem:
```python
from vedo import printHistogram
import numpy as np
d = np.random.normal(size=1000)
printHistogram(d, c='lb', logscale=True, title='my scalars')
printHistogram(d, c='red', horizontal=1)
```

<img width="331" alt="Screenshot 2021-03-29 at 00 19 22" src="https://user-images.githubusercontent.com/32848391/112769992-a49e6b00-9024-11eb-97e4-c6f6b7404631.png">

it would be nice to ditch my old implementation in favour of `plotext`.

**Comment by piccolomo** [comment]
Hi marcomusy,

I never tested the package on a mac terminal. I get the sense it is your terminal's problem.
Try giving this simple code and see what happens:
`print('█\n'*5)`

If the output is no working properly, it is definitively your terminals problem.

Did it work? It would be helpful knowing if it did. 

Thanks

**Comment by marcomusy** [comment]
yes - on a mac this is rendered as:

<img width="781" alt="Screenshot 2021-05-18 at 16 10 52" src="https://user-images.githubusercontent.com/32848391/118666634-a1895500-b7f3-11eb-8b12-db1d689a9cef.png">

(left on the "Terminus" application and right for the default terminal)
i guess it's not curable then ....
marco

**Comment by piccolomo** [comment]
Thanks for reply. 

then i would assume it is an issue of the mac terminal. Try check the terminal font properties, like interline etc... or try install another mac terminal (i have no idea which).

or Try using another character like `bar_marker = "x"` inside the `hist` function.

the output will look much less cooler but with no obvious spaces in different lines..

It would be nice to know what solution worked, for other people using mac!

thanks and good luck

**Comment by piccolomo** [comment]
P.S. I found [this article](https://www.maketecheasier.com/increase-line-spacing-terminal-mac/) about changing interline on mac terminal font.

**Comment by marcomusy** [comment]
Yes, you are right, by default the line spacing is set to 1 and I need to set it to 0.8 to get rid of the margins... except then all text looks clogged and hard to read .. so I guess we need to live with it..
Thanks anyway for addressing the issue!

**Comment by piccolomo** [comment]
no problem, if you find a better solution, keep posted

good luck
