### ISSUE TITLE
hist function use the last plot to set the upper limit

### ISSUE THREAD

**Issue by rlschuller** [piccolomo/plotext#18]
First of all, your lib is awesome : )

As a side-project, I'm working on a multi-format plotting utility, and your lib was an obvious first choice for the text output.

It's possible that I'm doing something wrong, but ylim/xlim seems to be set by the last histogram plot, and not the highest. Both scatter and line plots work well.

**Comment by piccolomo** [comment]
Hi rlschuller,

thanks for the feedback. Could you elaborate a little bit more? perhaps with a code.

The hist function is at its first verison and you are right there maybe be proplems. If you send the code I could repair for next version
thanks

**Comment by rlschuller** [comment]
![image](https://user-images.githubusercontent.com/11084889/118839526-ef0dcc80-b89c-11eb-89ca-38fe08434967.png)

**Comment by piccolomo** [comment]
Hi  rlschuller, you are right this is a bug and thanks for reporting.

Before I deal with it in next version, for now, I guess after calling the `hist` function and before the `show` function, you could try to extend the y limits using the `ylim` function.

Thanks and I will update. 
Savino

**Comment by piccolomo** [comment]
Hi @rlschuller,

the new version (3.0.0) of plotext is just available now at [this link](https://pypi.org/project/plotext/). Among the many changes, the new version solves the bug you kindly reported. The output of the second code you posted is now the expected one:
![image](https://user-images.githubusercontent.com/56689657/120876622-2f19c280-c5b2-11eb-9ff1-fe126274c377.png)
Hope it help.
Savino
