### ISSUE TITLE
Doesn't work with Windows Powershell?

### ISSUE THREAD

**Issue by Chaos99** [piccolomo/plotext#19]
I tried this with python(3) running in a windows PowerShell terminal.

It just produces a lot of strange control characters and beeping (probably the line-end bell) for a while and then stops.

I assume it's not compatible with this type of output terminal.
Might be worth a warning in the documentation/readme.

Or did I do something wrong?

Test was:
```python
import plotext as plx
y = [1, 2, 3, 4, 5]
plx.plot(y)
plx.show()
```
Windows 7
Python 3.8.8 (installed via WinPython)
plotext 2.3.1 (installed via pip)

**Comment by piccolomo** [comment]
Dear Chaos99,

I just tried your script using pyhton3.9.5 on a windows 10 enterprise machine with plotext 2.3.1 and it worked just fine. This is the output:
![image](https://user-images.githubusercontent.com/56689657/118662871-a26cb780-b7f0-11eb-9385-4cad8aa63b4e.png)

Could you upload your outplut? thanks

**Comment by Chaos99** [comment]
Based on your screenshot, you tried this in the Windows Command Prompt (cmd.exe). ([Command Prompt on Wikipedia](https://en.wikipedia.org/wiki/Cmd.exe))
I was using the Windows PowerShell (powershell.exe) ([PowerShell on Wikipedia](https://en.wikipedia.org/wiki/PowerShell))

**Comment by piccolomo** [comment]
You are right, it is awhile that i don't use windows. I have just tried powershell with the following result:

![image](https://user-images.githubusercontent.com/56689657/119846952-e0618e00-bf0a-11eb-999d-facadfbb2b60.png)

Using plotext  2.3.1 and Python 3.9.0 on Windows 10 Home and PowerShell 5.1.19041.906 

Try using Python 3.9? If the problem persists try using the function plt.nocolor()

If you want send the output of a simple plot-

**Comment by piccolomo** [comment]
Any updates? I will close the issue for now, but you can reopen it if needed.

Savino

**Comment by ashthespy** [comment]
Thanks for this library! 
I seem to be having some issues getting lines to show (vs dots) could it be related to Windows + Powershell as well? 
Here are some details
```
~> [Environment]::OSVersion

Platform ServicePack Version      VersionString
-------- ----------- -------      -------------
 Win32NT             10.0.19043.0 Microsoft Windows NT 10.0.19043.0


~> python --version
Python 3.9.1
~> pip show plotext
Name: plotext
Version: 3.1.3
Summary: plotext plots data directly on terminal
Home-page: https://github.com/piccolomo/plotext
Author: Savino Piccolomo
Author-email: piccolomo@gmail.com
License: MIT
Location: c:\programdata\miniconda3\lib\site-packages
Requires:
Required-by:
~> python -m plotext "import plotext as plt; y = plt.sin(100, 3); plt.plot(y); plt.plotsize(100, 30); plt.title('Plot Example'); plt.show()"
```
![image](https://user-images.githubusercontent.com/16233271/124359813-d7a95980-dc26-11eb-8f0a-671e2711f4b0.png)

```
python -m plotext "import plotext as plt; y1 = plt.sin(1000, 3); y2 = plt.sin(1000, 3, 1.5, phase = 1); plt.plot(y1, label = 'plot'); plt.scatter(y2, label = 'scatter', marker = 'small'); plt.plotsize(100, 30); plt.title('Multiple Data Set'); plt.show()"
```
![image](https://user-images.githubusercontent.com/16233271/124359881-1fc87c00-dc27-11eb-8eaf-6231f7b02978.png)

I have the same issue on windows terminal, Powershell, CMD, and alacrity.. So I don't think this is terminal specific issue?

**Comment by piccolomo** [comment]
Hi @ashthespy, it is by chance that I noticed that I haven't replied to you old post. 

Did the issue solve itself? I will publish a new version soon, perhaps you may want to try that as well. Feel free to re open the issue if necessary.
