### ISSUE TITLE
AttributeError: module 'plotext' has no attribute 'box'

### ISSUE THREAD

**Issue by coleramos425** [piccolomo/plotext#196]
Hello. I'm following your example for [Box Plot](https://github.com/piccolomo/plotext/blob/master/readme/bar.md#box-plot) implementation and am facing the following error:
```shell
line 156, in simple_box
    plt.box(
AttributeError: module 'plotext' has no attribute 'box
```
I've imported the module in my file and have confirmed installation. I'm using the latest `plotext==5.2.8`. Any ideas on why this might be happening?

Python Version: 3.10.12

**Comment by piccolomo** [comment]
Hi @coleramos425  sorry for late reply.

Try pip install git+https://github.com/piccolomo/plotext, to install the [GitHub version](https://github.com/piccolomo/plotext).

should work.

**Comment by coleramos425** [comment]
Thanks. I discovered that I needed to install from the repository rather than the latest PyPi release. That fixed the issue.

Is there an ETA for the next release? I've gotten a lot of value from the new functionality and would like to see this in the official module.

**Comment by piccolomo** [comment]
Hi @coleramos425, glad it helps. 

I am will make it available for next version. I have been working on rebuilding next version from scratch and I am taking more time then expected, as I want to be happy with the code. So far I have implemented the basic matrix of plots code as well basic plot building. 

There is still a long way as I need to finish all plotting tools (data points, lines, grids) and then then add all derived plots (bar plots, datetime , box plot etc). Then add docstrings, code comments and make a better documentation, possibly unit tests (as I keep on getting reminded about it). I just hope that March could be a realistic ETA. If there is any suggestions and request, now is the time.

**Comment by piccolomo** [comment]
Hi @coleramos425, and sorry for the very long wait for that release.

The box plot you were reading about lived only in the GitHub version at the time, which is why `pip install plotext` did not have it. That gap is about to close: version 6 of [plotext](https://github.com/piccolomo/plotext) is published very soon on GitHub and on  [PyPI](https://pypi.org/project/plotext/) together, box plot included:

  ```python
  import plotext as plt

  fig = plt.figure
  fig.draw(fig.box(["apples", "pears"], [[1, 2, 5, 9, 10], [3, 4, 6, 7, 8]]))
  fig.title("Box Plot")
  fig.show()
  ```

  Thanks for your patience, and regards,
  Savino
