### ISSUE TITLE
Ability to get the acsii-strings that is about to displayed.

### ISSUE THREAD

**Issue by garid3000** [piccolomo/plotext#20]
Thanks for really interesting library.
(IMHO) it could be more useful for to get the acsii-strings that is about to displayed without displaying on Terminal-Emulators.
So, with that strings, one can printout the plot over the Serial-Ports (i.e. pyserial), 
For example I have a need for live updating plot over UART for some real time application.

**Comment by piccolomo** [comment]
Hi garid3000 and thanks for feedback. 

You should be able to access the actual plot string using the parameter `plt.par.canvas`, while the actual character matrix could be retrieved using the parameter `plt.par.matrix`.

Thanks for suggestion anyway, I will add a proper function in next version to retrieve this parameter.

Did that help?
Savino

**Comment by garid3000** [comment]
Savino, Thanks, 
That line was exactly what I need to look at.

Also found another work around. 
(If anyone interested, I'll just comment here).
One can use "gnuplot" to get ASCII chart/matrix in the shell. 
So, it possible to run "gnuplot" using os.system or subprocess and retrieve that data-strings somehow.

But changing your library might easier than the this workaround.
So thanks again, 

Garid

**Comment by piccolomo** [comment]
Hi @garid3000,

the new version (3.0.0) of plotext is just available now at [this link](https://pypi.org/project/plotext/). Among the many changes, there is the possibility of accessing the plot string. Here is an example:
```
import plotext as plt
plt.plot([1, 3,  2])
plt.show(hide=1)
canvas = plt.get_canvas()
```
Hope it help.
Savino

**Comment by garid3000** [comment]
Thank you very much, works great !!!

**Comment by piccolomo** [comment]
Btw, now the function is called `plt.build()`
