### ISSUE TITLE
Feature request: Setting a maximum to bar plots

### ISSUE THREAD

**Issue by Isio-19** [piccolomo/plotext#201]
Hello, 
I've been using your library for a university project of mine and it's quite useful!
One issue that I have been encountering (with the bar plots, since that's what I'm mainly using) is that the "highest" bar in the bar plot is always "maxed out", by that I mean that the highest bar will take up the whole vertical space of the plot.

What I am requesting (if it's viable) is to set a "maximum" y (not sure about the naming scheme, called it maximum since there is a parameter called minimum) to the bar plot, so that the whole bar plot gets scaled down to show this maximum on the y axis.

Attached to the issue ticket is an image to illustrate what I'm asking.
![image](https://github.com/piccolomo/plotext/assets/62596663/284fc43b-04c7-4bed-a88d-d0847f15987c)
![image](https://github.com/piccolomo/plotext/assets/62596663/a4e65b2e-94b2-48d4-8a52-4f29061ed017)

This would allow us to make multiple bar graphs comparable between each other, despite not having the same "highest" bar.

**Comment by Isio-19** [comment]
My bad if a similar feature has already been requested/rejected or if such feature is already implemented.

Also another request that I have been thinking about would be to add a function to easily hide the labels/ticks on the x and/or y axis. I have found a work around for now (plt.yticks([500],["500"] when the max y is 100 for example)

**Comment by Isio-19** [comment]
I have found a workaround to achieve a similar result to what I was describing.

Code: 
```python
import plotext as plt

pizzas = ["Sausage", "Pepperoni", "Mushrooms", "Cheese", "Chicken", "Beef"]
percentages = [14, 36, 11, 8, 7, 4]

plt.bar([""], [100], color="white")
plt.bar(pizzas, percentages)
plt.title("Most Favored Pizzas in the World")
plt.show()
```

Output:
![image](https://github.com/piccolomo/plotext/assets/62596663/198de1a3-c5aa-419d-8cc6-5fd322a0d43f)

**Comment by piccolomo** [comment]
Hi @Isio-19, and sorry for the long silence.

  Both things you asked for were already there, just not easy to find.

  **The maximum.** Setting the *y* limits fixes the scale, so bars keep their true height and   several plots become comparable, which is exactly your goal: `plt.ylim(0, 100)` in the version you were using (see [plot limits](https://github.com/piccolomo/plotext/blob/master/readme/settings.md#plot-limits)),  no white helper bar needed.

  **Hiding the numbers.** `plt.yfrequency(0)` removes the numerical ticks of an axis
  (see [axes ticks](https://github.com/piccolomo/plotext/blob/master/readme/settings.md#axes-ticks)).

 In [plotext](https://github.com/piccolomo/plotext) ([PyPI](https://pypi.org/project/plotext/)) version 6, published soon on both, the same reads:

  ```python
  import plotext as plt

  pizzas = ["Sausage", "Pepperoni", "Mushrooms", "Cheese", "Chicken", "Beef"]
  percentages = [14, 36, 11, 8, 7, 4]

  fig = plt.figure
  fig.draw(fig.bar(pizzas, percentages))

  fig.ruler("y").lim(0, 100)     # the fixed maximum
  fig.ruler("y").ticks([])       # no numbers on that axis, frequency(0) does the same

  fig.title("Most Favored Pizzas in the World")
  fig.show()
  ```

  Your second request also earned a small change: an empty list of tick positions used to be
  ignored, and now removes the ticks, which is the obvious way to ask for it.

  Thanks for both suggestions, and regards,
  Savino

**Comment by Isio-19** [comment]
Thanks for the response! 
Haha, it has indeed been a long while, but all is good!
I don't work on the project that uses plotext, but if anyone ever needs something similar to what I needed, this ticket is here at least.

Thanks again!

**Comment by piccolomo** [comment]
dang it really was a long time. Freaking version 6 took my soul!
