### ISSUE TITLE
Line-thickness control?

### ISSUE THREAD

**Issue by thisismygitrepo** [piccolomo/plotext#207]
I'm reading the docs and I can only change plot size, I'm wondering if I can change the thickness of lines, as in those square blobs that make up the lines.

Thanks.

**Comment by thisismygitrepo** [comment]
I just zoomed out in terminal and that did the trick

**Comment by piccolomo** [comment]
Hi Alex, glad you found a way, although I was not sure about what you
meant. You meant line thickness?
- Savino

**Comment by thisismygitrepo** [comment]
meant like `linewidth` argument in `matplotlib`. It was too thick and is reducing the level of detail I can detect on x and y axes.

![image](https://github.com/piccolomo/plotext/assets/46288868/3c85c97e-7f99-4782-ab50-ccd9956131b3)

**Comment by piccolomo** [comment]
Oh got it, I thought you were referring to vertical/horizontal or axes
lines.

You cannot change the plot lines thickness but you can change the marker
character with the parameter (of most plotting functions) marker = 'x'
(insert the char you prefer) or you can use high definition code like
marker = 'hd', 'fhd' or 'braille' to plot in higher definition.

good luck
- Savino

**Comment by piccolomo** [comment]
PS I forgot to mention marker = 'sd' to plot the thickest lines.
- Savino

**Comment by piccolomo** [comment]
Hi @thisismygitrepo, and sorry for the very late formal answer.

  There is still no line thickness setting in version 6 of [plotext](https://plotext.readthedocs.io/en/latest/), and there cannot really be one: a terminal draws characters, so a line is as thick as the character used for it. What you choose instead is the **marker**, and that decides how heavy the line looks
  and how much detail fits:

  ```python
  import plotext as plt

  fig = plt.figure

  for code, phase in zip(("full", "hd", "braille"), (0, 0.4, 0.8)):
      fig.draw(fig.signal(plt.sin(phase = phase), marker = code).lines().label(code))

  fig.title("the marker sets how thick a line looks")
  fig.show()
  ```

  - `full` and `brick` are the heaviest, one whole character per point
  - `hd` splits each character into 2 × 2, `braille` into 4 × 2, so the line thins and the plot holds four to eight times the detail in the same space
  - any single character works too, `marker = "."` or `marker = "x"`, for the lightest line of all

  The [markers](https://plotext.readthedocs.io/en/latest/marker.html) page lists them, with the [higher resolution codes](https://plotext.readthedocs.io/en/latest/marker.html#higher-resolution-codes) section on the finer ones. On Windows, `hd` and `braille` draw while `fhd` does not.

  plotext 6 is out as a beta:

  - GitHub: https://github.com/piccolomo/plotext
  - PyPI: https://pypi.org/project/plotext/6.0.0b0/, installed with `pip install --pre plotext`
  - documentation: https://plotext.readthedocs.io/en/latest/

  Thanks for asking, and sorry it took this long to answer properly,

  Regards,
  Savino
