### ISSUE TITLE
Easiest way to plot a vertical line?

### ISSUE THREAD

**Issue by cassiobatista** [piccolomo/plotext#21]
Hey there!

I'd like to simulate a [stem plot](https://matplotlib.org/stable/gallery/lines_bars_and_markers/stem_plot.html#sphx-glr-gallery-lines-bars-and-markers-stem-plot-py). For that I think the easiest way might be using a regular scatter plot in combination with multiple vertical lines. However, I'm not sure how to draw those straight lines. Any ideas?

PS: This is really an awesome project. Keep it up!

**Comment by piccolomo** [comment]
Hi cassiobattista,

thanks for your feedback Try using the `fillx = True` option inside the plotting function you are using. 

From documentation:
 - `fillx = True` fills the area between the data and the x axis with data points (if used inside scatter) or line points (if used inside plot). For example: `plt.plot(data, fillx = True`). By default `fillx = False`
 - `filly = True` fills the area between the data and the y axis with data points (if used inside scatter) or line points (if used inside plot). For example: `plt.plot(data, filly = True)`. By default `filly = False`

Did it help?
Savino

**Comment by cassiobatista** [comment]
That worked like a charm @piccolomo, thank you so much! It looks more a bar chart than a stem plot, but that's fine by me.

I'm dropping a screenshot and a code snippet for reference :)

![Screenshot from 2021-05-20 08-04-38](https://user-images.githubusercontent.com/2287025/118968379-3d28db80-b942-11eb-8560-851fcf6cce24.png)

```python
    # @count_r and @count_h are OrderedDict()'s in the form x['aa'] = 0.99, x['ac'] = 0.25, etc.  
    logger.info("plotting via plotext")
    rticks = [x - 0.1 for x in range(len(count_r))]
    hticks = [x + 0.1 for x in range(len(count_h))]
    txp.scatter(rticks, count_r.values(), point_color='red',    fillx=True, label="baseline (pre VC)", point_marker=9)
    txp.scatter(hticks, count_h.values(), point_color='yellow', fillx=True, label="modified (post VC)", point_marker=8)
    txp.xticks(range(len(count_r)), count_r.keys())

    #txp.nocolor()
    txp.canvas_color("none") ; txp.axes_color("none") ; txp.ticks_color("white")
    txp.figsize(160, 40)
    txp.xlim([-0.5, len(count_r) + 0.1]) ; txp.ylim([0.0, 0.11])
    txp.xlabel("phoneme tokens") ; txp.ylabel("frequency (percentage, sums to 1)")
    txp.show()

```

**Comment by piccolomo** [comment]
Hi @cassiobatista ,

the newest version (3.0.0) of `plotext` is now available at [this link](https://pypi.org/project/plotext/). 

Among the many changes, the [stem plot ](https://github.com/piccolomo/plotext#bar-plot) is also available. 

Hope it help and thanks for help! 
Savino
