### ISSUE TITLE
(Feature) specific colors if the values meet a specific condition ( bigger or smaller than..etc) ?

### ISSUE THREAD

**Issue by z3ch5** [piccolomo/plotext#24]
I am wondering if there is a way to print some points with specific colors ( like if the points of (y) value are bigger than a defined number)

**Comment by piccolomo** [comment]
Hi z3ch5, 

would this example fit:

**Comment by piccolomo** [comment]
Sorry I closed by mistake, I will answer properly asap.

**Comment by piccolomo** [comment]
Hi @z3ch5 ,

about this example?

```
import plotext as plt

level = 0.3

n = 1000
y = plt.sin(n, 2.5)
x = range(n)
x1 = [x[i] for i in x if y[i] >= level]
x2 = [x[i] for i in x if y[i] < level]
y1 = [y[i] for i in x if y[i] >= level]
y2 = [y[i] for i in x if y[i] < level]

plt.clf()
plt.scatter(x1, y1, color = "green")
plt.scatter(x2, y2, color = "red")
plt.show()
```

![image](https://user-images.githubusercontent.com/56689657/122682772-b0e92d00-d1fb-11eb-9b21-bd23d23fda55.png)

would this fit your necessity? 

Thanks,
Savino

**Comment by z3ch5** [comment]
yes, it does !, thanks
