### ISSUE TITLE
feature request - function that returns the string version of the plot

### ISSUE THREAD

**Issue by evan0greenup** [piccolomo/plotext#35]
It would be nice to return the string value of the equivalent terminal plot.

**Comment by piccolomo** [comment]
Hi @evan0greenup,

thanks for feedback. Try the function `get_canvas()` which should do just that: it returns the plots as a string. If the color codes are not desired use also the function `colorless()` (in short `cls()`)

**Comment by piccolomo** [comment]
Hi @evan0greenup   ,

the new 4.0.0 version of `plotext` is now available on [github](https://github.com/piccolomo/plotext) and [pypi](https://pypi.org/project/plotext/). :-)

In it, the function that returns the plot canvas (without printing it) is called `plt.build()`. Let me know if you like it or what you think.

Thanks and all the best,
Savino
