### ISSUE TITLE
OSError: [Errno 25] Inappropriate ioctl for device

### ISSUE THREAD

**Issue by Dev-iL** [piccolomo/plotext#36]
I ran into the exact same issue described in [this question](https://stackoverflow.com/q/56817448/3372061). **TL;DR** - when running this library in PyCharm, the error in the subject is thrown by `utility.py>terminal_size()>os.get_terminal_size()`.

One of the fixes proposed in the Q&A worked for me, so I suggest replacing 

```diff
-return list(os.get_terminal_size())
+return shutil.get_terminal_size(fallback=(120, 50))
```

Or if you want to keep the existing code and provide a fallback,
```diff
-def terminal_size():
-    return list(os.get_terminal_size())
+import shutil
+ ...
+def terminal_size():
+    try:
+        return list(os.get_terminal_size())
+    except OSError:
+        return shutil.get_terminal_size(fallback=(120, 50))
```
Thanks!

P.S. I'm using Python 3.6 on Ubuntu 16.04 with PyCharm 2021.2.

**Comment by 4aHxKzD** [comment]
Tried this fix and it worked. Maybe you should open a Pull Request @Dev-iL

**Comment by piccolomo** [comment]
Hi @Dev-iL

thanks for the issue report and sorry for late reply! Your suggestion was not evil at all (considering your name: that's just a silly joke btw!), I will definitively  work on it for next version. 

In the meantime I wouldn't mind a pull request.

**Comment by Dev-iL** [comment]
@piccolomo Which of the solutions do you prefer?

**Comment by piccolomo** [comment]
Probably second. Your choice. I will work on it too for next version.

Thanks

**Comment by vincenzomanzoni** [comment]
@piccolomo : same things happens if you try to run plotext in Google Colab. Here the code to reproduce the issue:

`!pip install plotext`

```
import plotext as plt
y = plt.sin(100, 3)
plt.scatter(y, marker='.')
plt.plotsize(32, 8)
plt.title("Scatter Plot Example")
plt.cls()
plt.show()
```

**Comment by piccolomo** [comment]
Hi @Dev-iL and @vincenzomanzoni   ,

the new 4.0.0 version of `plotext` is now available on [github](https://github.com/piccolomo/plotext) and [pypi](https://pypi.org/project/plotext/). :-)

I have update the definition of the function `plt.terminal_size() `in the direction of your suggestion. I assume that this solves the issue, but feel free to reopen it, or give any kind of feedback.

Thanks and all the best,
Savino
