### ISSUE TITLE
Exception with yscale set to log

### ISSUE THREAD

**Issue by ethack** [piccolomo/plotext#37]
I'm getting the following error message.

```
Traceback (most recent call last):
  File "plot.py", line 10, in <module>
    plt.show()
  File "/usr/local/lib/python3.9/dist-packages/plotext/plot.py", line 420, in show
    _ylim_data(subplot)
  File "/usr/local/lib/python3.9/dist-packages/plotext/plot.py", line 540, in _ylim_data
    y_left = [_utility.log(subplot.y_left[s]) if subplot.yscale[0] == "log" else subplot.y_left[s] for s in range(subplot.signals_left)]
  File "/usr/local/lib/python3.9/dist-packages/plotext/plot.py", line 540, in <listcomp>
    y_left = [_utility.log(subplot.y_left[s]) if subplot.yscale[0] == "log" else subplot.y_left[s] for s in range(subplot.signals_left)]
  File "/usr/local/lib/python3.9/dist-packages/plotext/utility.py", line 283, in log
    return [math.log10(el) for el in data]
  File "/usr/local/lib/python3.9/dist-packages/plotext/utility.py", line 283, in <listcomp>
    return [math.log10(el) for el in data]
ValueError: math domain error
```
Here is my version of python and plotext.
```
Python 3.9.5 (default, May 11 2021, 08:20:37) 
[GCC 10.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import plotext
>>> plotext.__version__
'3.1.3'
>>> 
```

Here is the code to reproduce.
```python
import plotext as plt

dates = ('2021-06-21', '2021-06-22', '2021-06-23', '2021-06-24', '2021-06-25', '2021-06-26')
counts = (2910, 3326, 19308, 126939, 475620, 226890)

plt.bar(dates, counts)
plt.plotsize(100, 30)
plt.yscale("log")
plt.show()
```
Googling suggests that `math domain error` with a log means the value is 0 or negative. None of my original values are 0 or negative. But what's strange is that if I print out the value of `data` in the `plotext/utility.py:log(data)` function I get `[2910, 2910, 0, 0]`. `2910` is my first y value, but I don't know what's going on with the rest.

Am I doing something wrong with how I'm using the library? Linear bar plots seem to work fine for me.

**Comment by ethack** [comment]
Just saw this under "Future Plans" in the readme.

> log scale for bar/hist plot

So I'm thinking I'm trying to use a feature that's not implemented yet. Then can this count as a feature request instead of a bug report? :smile:

**Comment by piccolomo** [comment]
Hi @ethack 

the new 4.0.0 version of `plotext` is now available on [github](https://github.com/piccolomo/plotext) and [pypi](https://pypi.org/project/plotext/). :-)

The new version should solve the issue, you kindly reported. The bar plot has a parameter called `minimum` which can be used to alter the minimum level the bars reach. By default now it doesn't reach 0 and the log scale on the y axis should work just fine.
Please let me know i the issue persists or any other idea and feedback.

Thanks and all the best,
Savino
