### ISSUE TITLE
Incompatiblity with the dash plugin of pytest

### ISSUE THREAD

**Issue by jentrialgo** [piccolomo/plotext#38]
First of all, thank you very much for the package!

I've found a little issue: if I try to use [the dash package](https://pypi.org/project/dash/) and plotext at the same time, I get import errors when I execute pytest. I think it  is related to [this problem with the dash plugin for pytest](https://github.com/pytest-dev/pytest/discussions/8270).

A straightforward solution is deleting [this line from __init__.py](https://github.com/piccolomo/plotext/blob/9c78491e254c5768018fadf7912d5b0de1c8bf11/plotext/__init__.py#L10): it's an import of the `test` file that is not used later, but causes the problem with pytest.

In addition to that, maybe the name of the file `test.py` should be changed so that it doesn't name-shadows a standard library name, which in this case is [the internal package test](https://docs.python.org/3/library/test.html).

**Comment by piccolomo** [comment]
Hi @jentrialgo,

thanks a lot for the issue report and glad you like the package.

It seems a relevant matter. I am not an expert Pythoninst but I understand that I may need to create a testing function which doesn't conflict with  pytest for next version (it is going to take a few months to rewrite the code and add functionalities). 

Anyway I have installed pytest and then imported it after importing plotext with no issues. Any advice on how to spot the issue?

Thanks

**Comment by jentrialgo** [comment]
Hi,

I can reproduce the issue with these commands on a Ubuntu machine:

    mkdir issue
    cd issue
    python -m venv env
    source env/bin/activate
    pip install plotext
    pip install dash
    pip install pytest
    echo "import plotext as plt" > program.py
    pytest program.py

However, I've tried to use the corresponding commands in Windows and the issue doesn't appear, I don't know why. The only difference I see is slightly different versions of Python (3.8.6 in Ubuntu and 3.8.10 in Windows).

Anyway, to fix the issue, you just have to delete the `import test` in `__init__.py`. I can make a pull request if you like. 

In addition, I would name `test.py` something like `tests_plotext.py`.

I'm not an expert either, but when I create packages, I try to follow an structure like [this](https://docs.python-guide.org/writing/structure/). I use this command to generate it:

    cookiecutter https://github.com/audreyr/cookiecutter-pypackage

Thank you again for your work!

**Comment by piccolomo** [comment]
Hi @jentrialgo  

the new 4.0.0 version of `plotext` is now available on [github](https://github.com/piccolomo/plotext) and [pypi](https://pypi.org/project/plotext/). :-)

The new version should solve the issue, you kindly reported, by implementing the unittest environment for testing. 
The file is still called `test.py` (I forgot to change its name). 

Could you kindly let me know, if the issue is solved, otherwise I should change its name.

Thanks and all the best,
Savino

**Comment by jentrialgo** [comment]
Hi,

The issue with the name `test.py` seems to be solved. Thank you for being on top of this.

However, when I tried to reproduce the issue with the steps indicated in my previous message, I've found that `pip install plotext` didn't install all the required libraries: I had to manually install `Pillow` and `numpy`. Could this be another issue with plotext?

**Comment by jentrialgo** [comment]
Ah, I've just seen that issue I mention has already been reported as issue #53.

**Comment by piccolomo** [comment]
Great, I will solve the dependency issue for next version small update. 

Thanks for reporting anyway.
