### ISSUE TITLE
Issue with subplots? Maybe release hasn't been pushed in a while?

### ISSUE THREAD

**Issue by cjmcgraw** [piccolomo/plotext#39]
@piccolomo hey there. I am using your library in my project over at: https://github.com/cjmcgraw/docker-load-graph

Now there is clearly a problem on initial pip install. Specifically check out the following:

![image](https://user-images.githubusercontent.com/4107771/131385469-5d08ca29-5bbd-4a00-bfca-1627a3a49228.png)

The first command shows my application throwing an exception for python3.8 at line 765.

The second command shows I am using version `3.1.3` of plotext (the most recent/current)

The third command, show sme catting the file that throwed the exception, and grepping around the lines.

Clearly there is a distinct typo  `returnsa` instead of `return` there.

However in the current library I do not see that typo and thus don't have any immediate way of fixing this issue.

Could you please push the most recent changes you have in master to your release?

**Comment by cjmcgraw** [comment]
Specifically this issue only occurs when I have subplots that are missing data. Eventually they are filled in, but not initially.

Changing this "returnsa" to "return" completely fixes the problem on my local machine

**Comment by piccolomo** [comment]
Hi @cjmcgraw,

thanks a lot for taking the time to report this issue. The pip version of the package needs to be updated but the github version was corrected thanks to a pull request (Fix misspelling that crashes when x is not available. #25 by @whisller ).

I am in the process to rewrite the code from top to bottom which is going to take some time. 

I appreciate your encouragement and the project you have created, it looks really cool. Few suggestions about it to have more space for the plots:
 - if some plots share the same x axis, you could take these x axes away for all of plots except the bottom ones. Use the function `plt.xaxes(False)` if you are interested.
 -  if some plots share the same y axis, you could take these y axis away for all of plots except the left ones. Use the function `plt.yaxes(False)` if you are interested.
 - Same thing applies to the x and y labels: you could apply it only to the bottom plots. Use `plt.xlabel('')` and  `plt.ylabel('')` if interested.

All the best and please feel free to write any comment or bug report!

**Comment by piccolomo** [comment]
Hi @cjmcgraw,

Hi @ethack 

the new 4.0.0 version of `plotext` is now available on [github](https://github.com/piccolomo/plotext) and [pypi](https://pypi.org/project/plotext/). :-)

The new version should solve the issue, you kindly reported.

Please let me know i the issue persists or any other idea and feedback.

Thanks and all the best,
Savino
