### ISSUE TITLE
weired tick labels

### ISSUE THREAD

**Issue by huaiweicheng** [piccolomo/plotext#42]
I find it's very weired that the ticks of same value differs in the bar plot.
see 7.0-6.0, which is greater than 6.0-4.0 and 4.0-2.0
![image](https://user-images.githubusercontent.com/4011117/133601653-5b71c5aa-9d20-4b85-b9fc-ab87433ac5f9.png)

How is that happened?

**Comment by piccolomo** [comment]
Hi @huaiweicheng,

thanks for reporting this. Actually I think this is normal as the ticks labels are a rounded version of the actual ticks with the minimum amount of precision necessary to distinguish them, in order to have more space to write them.

**Comment by piccolomo** [comment]
Hi @huaiweicheng,

the new 4.0.0 version of `plotext` is now available on [github](https://github.com/piccolomo/plotext) and [pypi](https://pypi.org/project/plotext/). :-)

The new version should solve the issue, by adding an extra digit to the numerical ticks. 

Please let me know i the issue persists and feel free to give any other idea or feedback.

Thanks and all the best,
Savino
