### ISSUE TITLE
subplots broken

### ISSUE THREAD

**Issue by nj-vs-vh** [piccolomo/plotext#45]
Currently subplots functionality seems broken, even [`README` example](https://github.com/piccolomo/plotext#multiplie-subplots) do not work. Specifically, only first plot appears.

**Comment by nj-vs-vh** [comment]
Investigated a bit: seems like this behaviour has to do with second and subsequent plots being assigned height value of 0 because `height_max` is limited by a terminal size. I personally find this very counter intuitive because terminals inherently allow scrolling and it seems very logical for figure not to be limited by a terminal size, at least in height!

**Comment by piccolomo** [comment]
Hi @nj-vs-vh,

the new 4.0.0 version of `plotext` is available on [github](https://github.com/piccolomo/plotext) and [pypi](https://pypi.org/project/plotext/). 

The issue you mention, should be resolved in this version, but please let us know otherwise and feel free to reopen the issue. 

Savino
