### ISSUE TITLE
read from stdin

### ISSUE THREAD

**Issue by asartori86** [piccolomo/plotext#47]
Hi,
Thanks for this great tool. I think that plotext could shine even more by quickly plotting data from files and stdin. I wrote a small python script that allows me to plot from a pipe

```
$ ./process_data data.txt | plotext 1,3 # use first and third column
    ┌─────────────────────────────────────────────────────────────────────────────────────────┐
21.0┤                                                                                        ▝│
    │                                                                                         │
    │                                                                                         │
18.0┤                                                                                         │
    │                                                                                         │
    │                                                                                         │
15.0┤                                                                                         │
    │                                            ▖                                            │
    │                                                                                         │
11.0┤                                                                                         │
    │                                                                                         │
    │                     ▝                                                                   │
    │                                                                                         │
 8.0┤          ▗                                                                              │
    │                                                                                         │
    │                                                                                         │
 4.0┤    ▝                                                                                    │
    │                                                                                         │
    │  ▖                                                                                      │
   1┤▞                                                                                        │
    └┬─────────────────────┬─────────────────────┬─────────────────────┬─────────────────────┬┘
     1                    33.0                  64.0                  96.0                  128

```

@piccolomo, if you think this could be a good idea, I can provide a patch. If so, we should agree on the interface. I was thinking to ship an executable `plotext` that can quickly plot data from files and stdin like gnuplot does, but better :) 

```
plotext data.txt --type scatter --columns 1,3 1,5
cat data.txt | plotext --pipe --type scatter --columns 1,3 1,5
```

**Comment by piccolomo** [comment]
Hi @asartori86 ,

that sounds like a cool idea. Feel free to contribute. New version is coming relatively soon, perhaps I could incorporate your changes there as well.

**Comment by piccolomo** [comment]
Ciao @asartori86 ,

the new 4.0.0 version of `plotext` is now available on [github](https://github.com/piccolomo/plotext) and [pypi](https://pypi.org/project/plotext/). :-) it contains many new functions: new bar plots, matrix and image plots.

As I suspected though, your latest pull requested got removed, so you may need to send a new one.

Your command line tool is greatly appreciated and I should definitively credit you for it. Looking forward to it.

Thanks and all the best,
Savino

**Comment by jackmead515** [comment]
@asartori86 if you already got started, I can help develop. Looking to have this functionality as well.

**Comment by asartori86** [comment]
@jackmead515, if you clone the repo and then, from the master branch
```
python setup.py install
```
 you will have a nice plotext executable that reads both from stdin or file :)

@piccolomo, I see you didn't push to PyPI my patch yet

**Comment by piccolomo** [comment]
> @piccolomo, I see you didn't push to PyPI my patch yet

Hi @asartori86, sorry for delay, I am taking a break after big effort of new version. I could upload it for you on PyPi. Do you have a terminal command I could runt o directly upload from GitHub to PyPi without making a mess? Thanks

**Comment by asartori86** [comment]
@piccolomo, you should simply pull the updated master in your local folder and then redo the steps to publish to PyPI.

**Comment by piccolomo** [comment]
Hi @asartori86 @jackmead515   ,

thanks a lot for the issue report. I have published the new updates, which include the command tool, as version 4.1.0 on 
 both [github](https://github.com/piccolomo/plotext) and [pypi](https://pypi.org/project/plotext/).

Hopefully the tool will improve even further for next version. 

Thanks a lot for the contribution which is highly appreciated, 
Savino.
