### ISSUE TITLE
colorless() doesn't seem to persist

### ISSUE THREAD

**Issue by poposhka** [piccolomo/plotext#49]
a quick test for continuous updates below.

i must remove the comment in the for loop to allow the plot to remain colorless, following the "Streaming Data" example.

```
plt.xlabel("Samples")
plt.ylabel("Value")
plt.xlim(0,256)
plt.colorless()
frameno = ctypes.c_int32()

for n in range(0,100):	
	sslib.GetSnapshot(0,0, ctypes.byref(frameno), char_array.from_buffer(plotData), len(plotData))
	plotData = numpy.frombuffer(plotData, dtype=numpy.short)
	plt.cld()
	plt.clt()
	plt.title(f"{frameno}")
	plt.plot(plotData, marker="dot")	
	#plt.colorless()
	plt.show()
```

**Comment by piccolomo** [comment]
Hi @poposhka,

thanks for the issue report. The new 4.0.0 version of `plotext` is now available on [github](https://github.com/piccolomo/plotext) and [pypi](https://pypi.org/project/plotext/). :-) 

This version doesn't show the problem you kindly reported. I have tested it on this code

```
import plotext as plt
plt.clf()

plt.xlabel("Samples")
plt.ylabel("Value")
plt.xlim(0, 256)
plt.colorless() # plt.clear_color() is weaker but works just as well

for n in range(0,100):	
	plotData = plt.sin()
	plt.cld()
	plt.clt()
	plt.title("frameno")
	plt.plot(plotData, marker="dot")	
	#no need for plt.colorless() now
	plt.show()
```

Thanks and let us know if the issue persists, by reopening it or by giving any other related opinion.
