### ISSUE TITLE
plotsize in hide=True mode

### ISSUE THREAD

**Issue by jtplaarj** [piccolomo/plotext#50]
The resulting plot is the minimum of the current terminal and the defined `plotsize` regardless of the status of `hide`. I think that it would make more sense to use only plotsize when `hide=True`.

**Comment by piccolomo** [comment]
Hi @jtplaarj ,

the new 4.0.0 version of `plotext` is now available on [github](https://github.com/piccolomo/plotext) and [pypi](https://pypi.org/project/plotext/), which I believe solves the issue.

Feel free to reopen it if I am mistaken. Or give any other idea and feedback.

Thanks for the help and issue report.

All the best,
Savino.

**Comment by jtplaarj** [comment]
I understand that the new way of doing this is by using `plt.build()`. In my case, I run the script from VisualStudioCode and depending on the size of the terminal window, the final image changes its size. So, in my case, the issue is not solved.

**Comment by piccolomo** [comment]
Hi @jtplaarj, thanks for reply!

The plot size should be dependent on the terminal size. 

To allow bigger size use `plt.limit_size(False, False)` or simply `plt.limit_size(False)`. Its doc-string is available at `plt.doc.limit_size()`

Does it work?
Thanks, Savino

**Comment by jtplaarj** [comment]
It works perfectly, thanks!!!
