### ISSUE TITLE
plotsize with plt.build()

### ISSUE THREAD

**Issue by jtplaarj** [piccolomo/plotext#54]
When using plt.build, the size is dependent on the terminal. It may be more useful to only depend on plt.plotsize.

**Comment by piccolomo** [comment]
It should be dependent on `plt.plotsize()` if the size is smaller then the terminal. 

To allow bigger size use `plt.limit_size(False, False)` or simply `plt.limit_size(False)`. Its doc-string is available at `plt.doc.limit_size()`

Does it work?
Thanks, Savino

**Comment by jtplaarj** [comment]
It works perfectly. Thanks!!!!!
