### ISSUE TITLE
Consider making Pillow and numpy optional dependencies

### ISSUE THREAD

**Issue by ethack** [piccolomo/plotext#56]
I'd like to explain my use case:
- I have a project that I distribute as a docker container where one of my goals is a small total size.
- Pillow and numpy seem to only be needed for working with turning JPG images and the like into graphs. I won't be using this feature in my project. But overall the new features in v4.0 look fantastic!

Pillow and especially numpy are pretty heavy dependencies. Numpy is ~63 MB and Pillow is ~10 MB. In the context of my project this is a significant size.

I was wondering if you'd consider making Pillow and numpy optional dependencies that could be installed only if using the image graphing features? I think this could be done by moving the library imports so they are only called when that code path that needs them is executed. And then marking Pillow and numpy as [optional dependencies in setup.py](https://stackoverflow.com/questions/6237946/optional-dependencies-in-distutils-pip) (or I could work around this with `pip install --no-deps`).

If you plan to incorporate numpy into more features in the future, making plotext more dependent on it, then my request wouldn't make much sense to do.

**Comment by piccolomo** [comment]
Hi @ethack, thanks for the report and sorry for late reply (I put aside this project for awhile after the latest version update).

I think this is a brilliant idea, and should definitively work on it for next version (If I manage to understand properly how it works).

I wlll update and thanks.

**Comment by piccolomo** [comment]
Hi @ethack  ,

thanks a lot for the issue report. I should have sorted this in the newly updated 4.1.0 version, available on [github](https://github.com/piccolomo/plotext) and [pypi](https://pypi.org/project/plotext/).

Now `numpy` is no longer necessary in all cases and it is possible to install `pillow` only if necessary using `pip install plotext[image]`

Please let me know if the issue persists. 
Thanks and lll the best,
Savino.

**Comment by ethack** [comment]
That's fantastic news! Thank you so much!
