### ISSUE TITLE
Histogram

### ISSUE THREAD

**Issue by kris927b** [piccolomo/plotext#6]
Super cool package! Love the features. 😀

I was wondering if it was possible to add a way of creating histograms with this package. 📈
It would be super handy if the structure followed that of matplotlib just like your other functions does. 👨‍💻

**Comment by piccolomo** [comment]
Hi Kris927b,

thanks for your comment and I am glad you liked the package! :-)

Yours is a great suggestion I should definitively work on that in the near future. 
For the next version, I am now working on plottng the real point coordinates as the axis ticks, which is not as easy as it sounds. 

I will update on the histogram feature, any other idea (or bug) is welcomed! 

Savino

**Comment by piccolomo** [comment]
Hi Kris927b,

Tehre is a new version available at [pypi:plotext ](https://pypi.org/project/plotext/)and [github:plotext](https://github.com/piccolomo/plotext) but I still need to work on the histogram feature!

**Comment by david-macleod** [comment]
Also keen to seen the histogram feature 😄

**Comment by piccolomo** [comment]
Dear David,

Thanks for your comment and advise. The histogram feature is something that I will work on soon.

I will update.
Cheers

**Comment by piccolomo** [comment]
Hi Kris927b,

as by yours and others recommendation, I have added the **histogram** feature in the most update version (2.3.0) of `plotext`, which could be accessed at [this link](https://pypi.org/project/plotext/). 

I have not tested it that much, so any support, bug reports or ideas are very welcomed.

All the best in using this new feature and thanks for the query.
Savino
