### ISSUE TITLE
2 Feature Requests: Plot Extra Grid Lines and deal with 'None' Values in Data Plot

### ISSUE THREAD

**Issue by NLKNguyen** [piccolomo/plotext#65]
Hi,

The DateTime plot `plot_date` requires all values to be numeric (None/NaN/np.nan is not accepted), but it's useful to be able to display shorter lines that don't span the whole time frame, which requires a way to represent no data like None/NaN. What I'm trying to do is to add some arbitrary trend line/channel on a stock price series.
Can you support this?

Thanks!

**Comment by piccolomo** [comment]
Hi @NLKNguyen

thanks a lot for the issue report. However I find it a bit difficult to understand it. Could you kindly restate in simpler or different terms?

in particular, by values, you mean y values (not datetime ones)? if some y values are none/nan, how will this make the plot lines shorter? it seems to me, it would rather remove some of them (the one containing none/nan values) rather then shortening. 

Thanks for help

**Comment by NLKNguyen** [comment]
Thanks for the quick response,

I realized I used your API incorrectly. There is no issue. I'm used to other chart libraries that require all time series to share the same time frame and where there is no data, a NaN or None is expected.

Turned out multiple `plot_date` can have different dates as long as each has the same data length and date length. Here is just for reference.

```python
import pandas as pd
import plotext as plt

plt.datetime.set_datetime_form(date_form='%Y-%m-%d')

t1 = pd.date_range("2022-01-01", periods=5, freq="D")
x1 = [plt.datetime.datetime_to_string(el) for el in t1]
y1 = pd.Series([1,2,3,4,5], index=t1).tolist()
plt.plot_date(x1, y1,  marker = "hd", color=[1])

t2 = pd.date_range("2022-01-06", periods=5, freq="D") 
x2 = [plt.datetime.datetime_to_string(el) for el in t2]
y2 = pd.Series([6,7,8,9,10], index=t2).tolist()
plt.plot_date(x2, y2,  marker = "hd", color=[4])

t3 = pd.date_range("2022-01-03", periods=4, freq="D") 
x3 = [plt.datetime.datetime_to_string(el) for el in t3]
y3 = pd.Series([4,5,6,7], index=t3).tolist()
plt.plot_date(x3, y3,  marker = "hd", color=[3])

plt.canvas_color(0) 
plt.axes_color(0)
plt.ticks_color("bright-yellow")
plt.show()
```
 
![image](https://user-images.githubusercontent.com/4667129/147373517-64990fe1-f808-4217-89db-c43372c6b5c3.png)

Another question though, is there a way to show vertical lines on certain dates or horizontal lines on certain values? That would be similar to the existing Grid feature but only on specific locations.

Here is an example of an arbitrary vertical line when I use another lib called uniplot
![image](https://user-images.githubusercontent.com/4667129/147373596-9d06fb90-8707-4bbb-bed0-276b64af5836.png)

**Comment by piccolomo** [comment]
Hi @NLKNguyen, I have read your message and I liked your inputs, including the first one, which I think it is still valid (to plot data which include `None` values, if I am not mistaken) and shouldn't be too difficult to implement. 

The horizontal/vertical line feature sounds a little more difficult to implement as I would need to plot a line between the plotting limits, which are only known after the plot is done. Hopefully I will get an idea on how to do it properly for next version.

I will update.
Savino

**Comment by piccolomo** [comment]
Hi @NLKNguyen,

I think I solved both issues, in new GitHub [4.1.5 version](https://github.com/piccolomo/plotext). Here is the code:

```python
import plotext as plt
import numpy as np

plt.plot([1, 2, 3, None, np.nan, "nan", 2, 1])
plt.vertical_line(2.1, color = "red")
plt.horizontal_line(1.5, color = "green")

plt.show()
```
![image](https://user-images.githubusercontent.com/56689657/147697617-1c3b4f5f-3372-4d17-acf5-419a485c4046.png)

I haven't properly tested the new feature and functions. If you are available and double check, I could publish it on PyPi. 

Thanks for help and ideas (I have credited you [here](https://github.com/piccolomo/plotext/blob/master/readme/notes.md#credits).
Savino

**Comment by NLKNguyen** [comment]
OMG that's awesome. Great work! I'll surely test it out as soon as possible and let you know. Looks very promising.

**Comment by NLKNguyen** [comment]
It's very robust!! None/NaN is handled cleanly. Any combination I can think of works well. The horizontal/vertical lines with overlap effect look really nice. Well done! 
Being able to use the same dates for all series in a plot and can accept None/NaN is convenient when working with time-series data in tabular format like from SQL queries or Pandas Data Frames.
 
Thank you :)

![image](https://user-images.githubusercontent.com/4667129/147804195-6945f4ff-3456-4c46-aed8-14c3b2c27652.png)

```python
import pandas as pd
import plotext as plt
import numpy as np

plt.datetime.set_datetime_form(date_form='%Y-%m-%d')

t1 = pd.date_range("2022-01-01", periods=5, freq="D")
x1 = [plt.datetime.datetime_to_string(el) for el in t1]
y1 = pd.Series([1,2,None,4,5], index=t1).tolist()
plt.plot_date(x1, y1,  marker = "hd", color=1)

t2 = pd.date_range("2022-01-01", periods=10, freq="D") 
x2 = [plt.datetime.datetime_to_string(el) for el in t2]
y2 = pd.Series([None, None, np.nan, None, None, 6,7,8,9,10], index=t2).tolist()
plt.plot_date(x2, y2,  marker = "hd", color=4)

t3 = pd.date_range("2022-01-01", periods=10, freq="D") 
x3 = [plt.datetime.datetime_to_string(el) for el in t3]
y3 = pd.Series([np.nan, np.nan, 4,5,None,7, 8, np.nan,np.nan,np.nan], index=t3).tolist()
plt.plot_date(x3, y3,  marker = "hd", color=3)

t4 = pd.date_range("2022-01-01", periods=10, freq="D") 
x4 = [plt.datetime.datetime_to_string(el) for el in t4]
y4 = pd.Series([None, 3, 5, 7, None, 3, 4, 5, None, 4], index=t4).tolist()
plt.scatter_date(x4, y4,  marker = "hd", color=6)

plt.canvas_color(0) 
plt.axes_color(0)
plt.ticks_color("bright-yellow")

plt.horizontal_line(8.1, color = "red")
plt.vertical_line("2022-01-07", color = "green")

plt.horizontal_line(5, color = "blue")
plt.vertical_line("2022-01-09", color = "yellow")

plt.show()

```

**Comment by piccolomo** [comment]
Glad it worked :-), 

new [4.1.5 PyPi version](https://pypi.org/project/plotext/) also available now.

Thanks,
Savino
