### ISSUE TITLE
Strange Characters in Jupyterlab

### ISSUE THREAD

**Issue by logxen** [piccolomo/plotext#66]
Little bug I found here ... I am using Jupyterlab on Ubuntu 20.04 and I was getting the wide unicode block characters from a plot. I tried several different markers, (fhd, hd, dot, etc) and ended up with artifacts from previous markers on my plots. I eventually realized that this is because Jupyterlab is keeping the session open between the tests I was running and if I reset the python engine the artifact characters go away. Here is an example output having previously run the plot with fhd then hd:

![Screenshot from 2022-01-04 07-23-50](https://user-images.githubusercontent.com/1380142/148082508-be1c075d-833b-40d0-8960-191c770f5b16.jpg)

Thanks for a great tool! :)

**Comment by piccolomo** [comment]
Hi @logxen,

thanks a lot for reporting this. 

I played around with jupyter-lab and luckily this should be solved just by using a clear function, before the plotting one: namely `clp()` or` clf()`. The complete guide on clear functions is [here](https://github.com/piccolomo/plotext/blob/master/readme/utilities.md#clear-functions).

Here is an example that worked well with me, with multiple plotting calls:
![image](https://user-images.githubusercontent.com/56689657/148114835-30eb0e67-98f5-431f-a8a4-3c6071dc59b7.png)

Let me know if works for you as well.

All the best,
Savino

**Comment by piccolomo** [comment]
Hello @logxen, any update? Can I close the issue?

**Comment by logxen** [comment]
sorry for the delayed response ... yes, the clear functions work, thanks!

**Comment by piccolomo** [comment]
👍🙂
