### ISSUE TITLE
Legend Missing in Bar Plots if First Bar is 0

### ISSUE THREAD

**Issue by barbestack** [piccolomo/plotext#68]
If the first data element in the list is 0, the Legend does not display the associated color.
```
>>> import plotext as plt
>>> dates = ['2022-01-01', '2022-01-02', '2022-01-03']
>>> dayc = [0, 1, 0]
>>> plt.bar(dates, dayc, label="Day")
>>> plt.plotsize(180, 40)
>>> plt.show()
```
![image](https://user-images.githubusercontent.com/11821973/148624600-f8395007-edbe-4e66-b193-511c2942c969.png)

Same for a stacked_bar:
>>> import plotext as plt
>>> dayc = [0, 1, 0]
>>> nightc = [1, 0, 0]
>>> dates = ['2022-01-01', '2022-01-02', '2022-01-03']
>>> plt.stacked_bar(dates, [dayc, nightc], label=["Day", "Night"])
>>> plt.plotsize(180, 40)
>>> plt.show()
![image](https://user-images.githubusercontent.com/11821973/148624691-74b4b26c-7013-4392-803a-d32ada8b582b.png)

**Comment by barbestack** [comment]
Works fine if first data elements are non-zero (even if the rest are zero)
![image](https://user-images.githubusercontent.com/11821973/148624783-f21c58f9-479c-4636-abc4-df810ea52725.png)

**Comment by piccolomo** [comment]
Thanks a lot, taking some time to come back to the project. I will update. Really appreciate the reports!

**Comment by piccolomo** [comment]
Hi @barbestack,

very good issue report. I found the solution and now the code:
```python
import plotext as plt
dates = ['2022-01-01', '2022-01-02', '2022-01-03']
days = [0, 1, 0]
plt.bar(dates, days, label = "label")
plt.show()
```
outputs the right result:
![image](https://user-images.githubusercontent.com/56689657/152647577-8d0a24e6-38f2-4ac0-a256-3f773cd4b97c.png)
You can download the latest GitHub [4.1.7 version](https://github.com/piccolomo/plotext) (not yet available on PyPi) using: 
```console
pip install git+https://github.com/piccolomo/plotext
```
note: you need git installed to be able to run the latest command.

Could you kindly double check that it actually solve the issue for you as well?

Thanks,
Savino
