### ISSUE TITLE
input() not working

### ISSUE THREAD

**Issue by edenroseFR** [piccolomo/plotext#69]
This is the output when I tried using input()
![image](https://user-images.githubusercontent.com/65489091/148660245-7a108b72-533b-49a4-85f2-afe62e5fa3da.png)

**Comment by piccolomo** [comment]
Hi @edenroseFR, thanks for issue reporting.

I had a quick check on few of my ubuntu terminals and everything went well. 

What terminal/shell are you using?

Thanks,
Savino

**Comment by edenroseFR** [comment]
@piccolomo , I'm using Windows.

**Comment by piccolomo** [comment]
> @piccolomo , I'm using Windows.

and what software to run python scripts?

**Comment by edenroseFR** [comment]
I tried VS Code terminal and Command Prompt. Both have the same result.

**Comment by piccolomo** [comment]
Hi @edenroseFR,

thanks a lot for this issue report. I think I understood where the error came from. It seem to originate from the line 
```
import win_unicode_console
win_unicode_console.enable()
```
in the `_utility\platform.py `file. Those lines are now commented in new 4.1.6 version, and the error should not come again. 

You can download latest GitHub version with: 
```console
pip install git+https://github.com/piccolomo/plotext
```
Did it work?
thanks,
Savino

**Comment by edenroseFR** [comment]
Worked like a charm. Thank you!
