### ISSUE TITLE
Support for Datetime Axis

### ISSUE THREAD

**Issue by geoffrey-eisenbarth** [piccolomo/plotext#7]
Wanted to say that I love this library and it has been super useful!

I am interested in helping add datetime support for the x-axis if it's something you're interested in. The particular case I'm thinking of is using a pandas Series with a datetime index. I haven't had a chance to dig into the source code yet, but was hoping to gauge interest in this kind of support and perhaps get pointers for where to start looking in the code. It seems like the x-axis must be integer based, which I assume is due to methods in place that scale the x-axis to fit into 80 lines. Hopefully I'll have time to get a better grasp of the ins and out of the code soon, but it would be great if we could work towards datetime-oriented axes.

If I've somehow missed the fact that this is possible with the library as is, please forgive me: I've only had a few days with the library.

Thanks!

**Comment by piccolomo** [comment]
Hi geoffrey-eisenbarth,

thanks a lot for your comment, I am glad you are enjoying the package! 

For sure I would be interested in collaborating to include date-time support in the package. 
I am now dealing with showing the real coordinates in the x and y axis for the next package update so your comment comes at the right time. 

I am now busy with work but we could plan what to do and the functions needed to add the support, if you are still interested. What do you think?

Thanks and talk soon,
Savino

**Comment by piccolomo** [comment]
Hi geoffrey-eisenbarth,

just in case you are still interested, I have just uploaded a new `plotext`  version. The documentation ia available at  [pypi: plotext ](https://pypi.org/project/plotext/) and [github: plotext](https://github.com/piccolomo/plotext).

The package can be upgraded using `pip install plotext --upgrade` 

all the best.

**Comment by matthewhanson** [comment]
This is really neat library! 

I'm also very interested in datetime support for the x-axis on histograms and plots. I'm using this in a CLI for querying geospatial data and quickly plotting values, but datetime is the most useful (to quickly see the temporal distribution of satellite images for instance).

I took a quick look at the code but there's a lot of moving parts so wasn't sure of where the main logic was that would need to be updated.  Histograms are a bit more complicated than regular plotting as the binning will need to be done on the date fields.

**Comment by piccolomo** [comment]
Hi matthewhanson,

thanks for the reply, and I am glad you like the library. That is a feature I would definitively work on (in my free time from work which is not a lot).

I guess the first thing to understand is what is the standard used in Python to express dates and times and secondarily to create a function which given a list of dates (in the format chosen) returns a list of numbers spaced the right amount between one another equal to the time differences and a list of time labels as strings: the lists can be used to plot dates using the plt.xticks() function. what do you think?

any help is welcomed.

**Comment by piccolomo** [comment]
Hi @matthewhanson and @geoffrey-eisenbarth,

the newest version (3.0.0) of `plotext` is now available at [this link](https://pypi.org/project/plotext/). 

Among the many changes, one can now also [plot dates and times](https://github.com/piccolomo/plotext#date-time-plot). 

Hope it help and thanks for help! 
Savino
