### ISSUE TITLE
Plot Refresh Rate

### ISSUE THREAD

**Issue by linan0827** [piccolomo/plotext#72]
This is an excellent project which I have been dreaming about for a long time.

I am not an expert on terminal manipulation, so I have a very basic question as the title suggested. I am curious about this is because normally I need to log in to a remote machine and use this tool to plot some data collected on that machine. The connection bandwidth is limited so I would like to estimate what can be the maximum refresh rate my data plotting loop could be.

Thanks again for this tool and the possible answer.

**Comment by piccolomo** [comment]
Hello @linan0827  glad you enjoying this project :-),

after you plot some data and show it with the `show `function, you could check the time it took to process the plotting (only inside the `show `function) with the function `time`, which will return the computational time required for computation. Its reciprocal should give an estimate on the refresh rate.

For example:
```
import plotext as plt

plt.plot([1,3,2])
plt.show()
t = plt.time()
```

Thanks and I hope it worked!,
Savino

**Comment by piccolomo** [comment]
hello, any update?

**Comment by piccolomo** [comment]
i closed for lack of feedback.
