### ISSUE TITLE
xticks() Not Working with Datetime Plots

### ISSUE THREAD

**Issue by saddy001** [piccolomo/plotext#73]
```
Traceback (most recent call last):
...
  File "./main.py", line 87, in plot_graph
    plt.xticks(atop_log.Time[::2])
  File "/home/user/miniconda3/lib/python3.8/site-packages/plotext/_figure.py", line 230, in xticks
    ticks = list(map(_utility.string_to_time, ticks)) if len(ticks) > 0 and type(ticks[0]) == str else ticks
NameError: name '_utility' is not defined
```
I tried to fix it, but it is not easily possible, because _utility.string_to_time now seems to be in a class (plotext._datetime.datetime_class.string_to_datetime) that needs plt as constructor.

**Comment by piccolomo** [comment]
Hi @saddy001 ,

thanks for the issue report! Could I have a snippet of the code that produced this error? 

Thanks

**Comment by saddy001** [comment]
It fails with _any_ piece of code. Just call plt.xticks.

**Comment by saddy001** [comment]
Sorry I found out this is specific to plt.plot_date.

**Comment by piccolomo** [comment]
Hi @saddy001,

thanks a lot for the report. I got some time to solve it. In fact this code:
```python
import plotext as plt
plt.datetime.set_datetime_form(date_form = '%d/%m/%Y')
dates = ["12/11/1980", "13/12/1982"]
prices = [2, 1]
plt.plot_date(dates, prices)
plt.xticks(dates, ["first", "last"])
plt.plotsize(100, 30)
plt.show()
```
outputs:
![image](https://user-images.githubusercontent.com/56689657/152647091-f83ea04f-c570-46ce-ab57-32c1186944a1.png)

You can download the latest GitHub [4.1.7 version] (https://github.com/piccolomo/plotext) (not yet available on PyPi) using: 
```console
pip install git+https://github.com/piccolomo/plotext
```
note: you need git installed to be able to run the latest command.

Could you kindly double check that it actually solve the issue for you as well?

Thanks,
Savino
