### ISSUE TITLE
Idea: matplotlib backend mode

### ISSUE THREAD

**Issue by wookayin** [piccolomo/plotext#75]
Hi! I found this library and it's very interesting. Thanks for the great library.

One immediate thought I have is that its programmatic interface is quite independent. I wish I would be able to use the same matplotlib code for drawing plots, so implementing a matplotlib backend or (some sort of wrapper) would be great.

The API showcased in https://github.com/piccolomo/plotext/blob/master/readme/subplots.md follows the legacy `plt.` matplotlib API, which I think is bad and should be [discouraged](https://matplotlib.org/matplotblog/posts/pyplot-vs-object-oriented-interface/).

**Comment by piccolomo** [comment]
hi @wookayin,

thanks a lot for dropping your idea: very much appreciate any contribution :-)

I did not entirely understood it tough. Is it that you would like plot with `matplotlib` and see the same result in terminal without having to rewrite the same code for `plotext`?  

Or more that you would like an output (wrapper) from `plotext` to connect to `matplotlib`? In this case, one thing that comes to mind is that I have created an alternative to `show()`, called `build()`, which outputs the plot as a string without printing it. To which input of `matplotlib` should connect it? 

Would `plx.` be a good alternative to `plt. `

Thanks,
Savino

**Comment by wookayin** [comment]
I looked into a bit of how this could be realized, and a tentative conclusion is due to much design differences this would not be easily possible.

The matplotlib backend API requires implementation of figure manager (which is straightforward) and renderer. The renderer is supposed to draw graphics being rendered from *matplotlib-internal* data structures (such as Figure, SubplotAxes). Mostly the renderer would need to implement how to draw path, image, and text, but the current implementation of plotext has nothing to do with matplotlib internal APIs and has their own replication of similar concepts. So writing an adapter or bridge is not straightforward (unless a huge refactoring and modularization happens), and this library is designed to do simple plotting jobs based on its own interface which is not compatible with matplotlib.

I will close this issue for now, but if you have any other thoughts I'd be happy to discuss more.

**Comment by piccolomo** [comment]
Hi @wookayin,

thanks a lot for the great idea. I am now in the process of writing some code for next version, which will require a long time i suppose, but I still think this idea is actually quite interesting and I may give it a go if I realise is doable. 

The only think i could think for now is, at the end of `matplotlib` plotting code to add a `plotext` function which take `matplotlib` `Figure` object and extracts all data necessary for a terminal plot. I am quite concerned already when plotting multiple subplots and forn lines, grid, coloring etc... quite a job but I perhaps it could be improved with time. :-)

Thanks and any other idea is welcomed,
Savino

**Comment by piccolomo** [comment]
Hi @wookayin,

I have worked on your request and added the function `from_matplotlib()` function, in the new [version 5.1](https://github.com/piccolomo/plotext), available only on GitHub for now, using:
```console
pip install git+https://github.com/piccolomo/plotext
```
The function is described [here](https://github.com/piccolomo/plotext/blob/master/readme/environments.md#matplotlib) and you have been credited [here](https://github.com/piccolomo/plotext/blob/master/readme/notes.md#credits).

Any feedback or double test is appreciated :-).
Thanks and all the best,
Savino
