### ISSUE TITLE
Streaming data flickering

### ISSUE THREAD

**Issue by ThSGM** [piccolomo/plotext#8]
I tried to code up an example with streaming data but it flickers quite poorly. Am I doing something wrong? 

```
import plotext.plot as plx
import numpy as np

pi = np.pi
x = np.linspace(0, 2*pi, 50)
y = np.sin(x)
t = np.linspace(0, 2, 50)

plx.clear_terminal()
plx.scatter(x,y,point_color="red", point_marker="o")
plx.set_cols(100)
plx.set_rows(100)
plx.set_ylim([-1.1,1.1])
plx.set_xlim([0,2*pi])
plx.set_axes_color("green")
plx.set_background("black")
plx.set_spacing([5,8])
plx.show()

for tt in t:
        plx.clear_plot()
        plx.clear_terminal()
        y = np.sin(x-tt)
        plx.scatter(x,y)
        plx.show()
        plx.sleep(0.1)


```

**Comment by piccolomo** [comment]
Hi ThSGM,

thanks for the comment. I tried your code and it worked well on my machine. I would try to tweak the sleeping time in `sleep(time)` to adapt it to your machine. Also notice that when the plot clears, it clears also all the plot style. 

Here is the revised code:

`#!/usr/bin/env python3
import plotext.plot as plx
import numpy as np

pi = np.pi
n_points = 50
x = np.linspace(0, 2 * pi, n_points)
y = np.sin(x)
t = np.linspace(0, 2 * pi, n_points)

for tt in t:
    plx.clear_plot()
    plx.clear_terminal()
    
    y = np.sin(x - tt)
    plx.scatter(x, y)
    plx.set_cols(100)
    plx.set_rows(100)
    plx.set_ylim([-1.1, 1.1])
    plx.set_xlim([0, 2 * pi])
    plx.set_axes_color("green")
    plx.set_background("black")
    plx.set_spacing([5, 8])
    
    plx.sleep(0.2)
    plx.show()
`

Let me know if you find a way to make it work. Thanks
