### ISSUE TITLE
[Usage Question] How to Plot Time Series? 

### ISSUE THREAD

**Issue by MartinThoma** [piccolomo/plotext#83]
In my [`activity-tracker`](https://github.com/MartinThoma/activity_tracker) project I have simple a list of timestamps. If there is a timestamp, then there is activity.

I would like to create a plot for one day of recorded activity. It should be a a 1440 pixel graphic (24 hours * 60 minutes / hour) x e.g. 20 pixel. Hence `x = h * 24 + m` (for any `y`) just indicates if that time is in my timeseries.

Doing it with PIL:

```
from datetime import datetime, date
from typing import List

def create_day_plot(timestamps: List[datetime], day: date) -> None:
    print(f"{day.strftime('%Y-%m-%d')} -- {len(timestamps)}")
    from PIL import Image
    img = Image.new(mode="RGB", size=(24*60, 20), color='white')

    pixels = img.load() # create the pixel map

    for timestamp in timestamps:
        if timestamp.strftime("%Y-%m-%d") != day.strftime("%Y-%m-%d"):
            continue
        x = timestamp.hour * 60 + timestamp.minute

        for y in range(img.size[1]):
            pixels[x, y] = (255, 0, 0)

    img.save("plot.png")

# Just a tiny sample:
create_day_plot([datetime(2022, 3, 27, 12, 0, 0), datetime(2022, 3, 27, 12, 1, 0), datetime(2022, 3, 27, 12, 2, 0)], date(2022, 3, 27))
```

With a bit more relaistic data it looks like this:

![foo](https://user-images.githubusercontent.com/1658117/160284512-90b05d84-7daf-4e25-b8f0-0464a3d737f6.png)

Is this possible with plotext? (If the answer is "try to make it work with matplotlib first", then I'll ask this on StackOverflow, but maybe there is a way to control the output on pixel-level? :-) )

**Comment by piccolomo** [comment]
Hi @MartinThoma,

thanks a lot for the great input. Here is my draft solution:

```python
import plotext as plt
from random import randint
from datetime import datetime

plt.clf(); 
#plt.clt(); # to optionally clean the terminal
plt.datetime.set_datetime_form(date_form="", time_form="%H:%M")

times = [datetime(2022, 3, 27, randint(0, 23), randint(0, 59), randint(0, 59)) for i in range(100)] # A random list of times during the day
times = [plt.datetime.datetime_to_timestamp(el) for el in times]

for el in times:
   plt.vertical_line(el, color="red")
xlabels = [plt.datetime.datetime_to_string(datetime(2022, 3, 27, i, 0, 0)) for i in range(24)]
xticks = [plt.datetime.datetime_to_timestamp(datetime(2022, 3, 27, i, 0, 0)) for i in range(24)]
plt.xticks(xticks, xlabels)
plt.frame(0)
plt.xaxis(1, "lower"); plt.xaxis(1, "upper")
plt.xlabel("Hours in The Day")
plt.title("Activity Tracker")
plt.plotsize(None, 20)
plt.show()
```
with this result:
![image](https://user-images.githubusercontent.com/56689657/160436796-e885bd50-b170-482d-bf90-f10aced7f389.png)

For some reason I have to convert the `datetime` objects in timestamps as I discovered `plt.vertical_lines() `is not able to handle them: I should fix this for next version.

I hope it helps. What do you think? :-)

Thanks,
Savino

**Comment by piccolomo** [comment]
Hi @MartinThoma,

it occurred to me that you could improve the pixel resolution using this other way:

```python
import plotext as plt
from random import randint
from datetime import datetime, timedelta

plt.clf(); 
plt.clt(); # to optionally clean the terminal
plt.datetime.set_datetime_form(date_form="", time_form="%H:%M") # Try also time_form="%H" for clearer x ticks !  

times = [datetime(2022, 3, 27, randint(0, 23), randint(0, 59), randint(0, 59)) for i in range(100)] # A random list of times during the day
times = [plt.datetime.datetime_to_timestamp(el) for el in times] # I will need to fix this; datetime_to_string should have worked.

plt.scatter(times, [1] * len(times), fillx = 1, marker = 'hd', color = 'red')
xticks = [datetime(2022, 3, 27) + timedelta(hours=i) for i in range(25)] 
xticks, xlabels = list(map(plt.datetime.datetime_to_timestamp, xticks)), list(map(plt.datetime.datetime_to_string, xticks))
plt.xticks(xticks, xlabels); plt.yticks();
plt.xlim(xticks[0], xticks[-1]); plt.ylim(0, 1);
plt.frame(0)
plt.xaxis(1, "lower"); plt.xaxis(1, "upper")
plt.xlabel("Hours in The Day")
plt.title("Activity Tracker")
plt.plotsize(None, 20) # Set the height you prefer or comment for maximum size 
plt.show()
```
with this result:
![image](https://user-images.githubusercontent.com/56689657/160590972-07d2761e-d3f2-4d2f-b601-5489ab495301.png)

**Comment by MartinThoma** [comment]
wooooah, this is amazing! Thank you so much! :hugs:

**Comment by MartinThoma** [comment]
This answers my question in way more detail than I expected! You are awesome!

**Comment by piccolomo** [comment]
Great, happy it helped! :-)

**Comment by piccolomo** [comment]
Hi @MartinThoma ,

Thanks to your request, I have added the function `eventplot()` function, in the new [version 5.1](https://github.com/piccolomo/plotext), available only on GitHub for now, using:
```console
pip install git+https://github.com/piccolomo/plotext
```
The function is described [here](https://github.com/piccolomo/plotext/blob/master/readme/other.md#event-plot) and you have been credited [here](https://github.com/piccolomo/plotext/blob/master/readme/notes.md#credits).

Any feedback or double test is appreciated :-).

Thanks and all the best,
Savino

**Comment by MartinThoma** [comment]
You're amazing! Thank you for giving credit - that would not be necessary, but I appreciate it 😊🤗

**Comment by ryanwwest** [comment]
Hi, I have a similar question but for a different type of data. I'm currently using the `rectangle` function to plot data instead of `scatter`, with the following X data (timestamps) and Y data (frequency bands):

```
Start Freq=3590.0, End Freq=3600.0, Start TS=2023-07-10T00.00.00, End TS=2023-07-31T00.00.00
Start Freq=3550.0, End Freq=3590.0, Start TS=2023-07-10T00.00.00, End TS=2023-07-12T20.00.00
Start Freq=3550.0, End Freq=3590.0, Start TS=2023-07-14T12.00.00, End TS=2023-07-31T00.00.00
```
My plot looks like this (note how the X axis shows numbers, as using a Python timestamp for any `rectangle` parameters gives `TypeError: must be real number, not datetime.datetime`):
![image](https://github.com/piccolomo/plotext/assets/31378238/238e1ee9-4df7-4adf-a456-78aaf1f93389)

I've thus been translating the above timestamps into the numbers as they appear in the graph as follows:
```
for a in spectrum_allocations:
    start_ts = datetime.strptime(a.start_timestamp, "%Y-%m-%dT%H.%M.%S").timestamp()/100
    end_ts = datetime.strptime(a.end_timestamp, "%Y-%m-%dT%H.%M.%S").timestamp()/100
    plt.rectangle(x=[start_ts, end_ts], y=[a.start_frequency,a.end_frequency],  color=colors.pop(), fill=True)
```

Obviously this isn't ideal. Is there any way I could still get the same looking graph, yet have the X axis display human-readable timestamp information?
