### ISSUE TITLE
Feature Request: Reverse Axes

### ISSUE THREAD

**Issue by pieterbergmans** [piccolomo/plotext#86]
This is a great library and very easy to use. Thanks!

My question is, is there anyway to reverse the x-axis?  My data is in descending order but the plotext plots it in ascening order.

Thanks.

**Comment by piccolomo** [comment]
Hi @pieterbergmans,

sorry for late reply, I worked on latest version. I do not have this feature in the package, but sounds like something I could integrate, but not too sure.

In the mean time have you tried to reverse the x data with `x[::-1]` and to change the x ticks to the reversed ones with `plotext.xticks()`? 

all the best and thanks a lot for the issue report

**Comment by piccolomo** [comment]
Hi @pieterbergmans, I am finally working on your idea. Here is a result:

![image](https://user-images.githubusercontent.com/56689657/187877873-76435675-253b-4898-bf2c-db9a33006833.png)

I still have to upload the code. Any feedback welcomed.

**Comment by piccolomo** [comment]
Hi @pieterbergmans, I finally updated `plotext` including the changes you asked for. 

I introduced the function `interactive()`, but haven't tested properly so any feedback is welcomed. 

The new version is available [on GitHib](https://github.com/piccolomo/plotext) and soon also [on PyPi](https://pypi.org/project/plotext/). To install follow the indications [here](https://github.com/piccolomo/plotext#install).

Your changes are documented [here](https://github.com/piccolomo/plotext/blob/master/readme/utilities.md#useful-functions) and you have been credited [here](https://github.com/piccolomo/plotext/blob/master/readme/notes.md#credits).

Thanks a lot for your inputs and all the best,
Savino
