### ISSUE TITLE
SyntaxError in new Version

### ISSUE THREAD

**Issue by Neo-Oli** [piccolomo/plotext#87]
Hi

In the latest release there is a syntax error in __init__.py. 

Tested with this very basic example:
```
$ pip install plotext
Collecting plotext
  Using cached plotext-5.0.0-py3-none-any.whl (1.8 MB)
Installing collected packages: plotext
Successfully installed plotext-5.0.0
$ cat test.py 
#!/usr/bin/env python
import plotext as plt
y = plt.sin() # sinusoidal signal 
plt.scatter(y)
plt.title("Scatter Plot")
plt.show()
$ ./test.py 
Traceback (most recent call last):
  File "/root/./test.py", line 2, in <module>
    import plotext as plt
  File "/usr/lib/python3.9/site-packages/plotext/__init__.py", line 4
    __version__ = "5.0.0"from plotext._core import *
                         ^
SyntaxError: invalid syntax
```

However in this repository the syntax seems correct. Is the source on PyPI not the same as in this git repository?

**Comment by piccolomo** [comment]
Hi @Neo-Oli ,

thanks a lot for letting me know. Very helpful! Not sure where that error came from. Anyway I updated the version! 

Could you kindly update if the new package works? 

Any other issue or feedback (positive or negative), please let me know. I may take a rest for a while, but will answer eventually.

All the best,
- Savino

**Comment by Neo-Oli** [comment]
Thanks for the quick fix, it works now.
