### ISSUE TITLE
Function limit_size() not Working as Usual

### ISSUE THREAD

**Issue by Neo-Oli** [piccolomo/plotext#88]
Hey

`limit_size()` no longer seems to be working. If i set it to `False, False` the plot will still be limited to the terminal size. In the previous version this worked to create bigger plots. Because I am not running it from a terminal it will always be limited to `80x24` now

```
#!/usr/bin/env python
import plotext as plt
y = plt.sin()
plt.scatter(y)
plt.plot_size(200, 300)
plt.limit_size(False,False)
plt.title("Scatter Plot")
plt.show() 
```

**Comment by piccolomo** [comment]
yes true, but it should work with plotsize as well, hopefully. The default
unlimited size is preaty big, so i gave the terminal as a first reference.

does it work with plotext()?

thanks a lot for reporting! 🙂

**Comment by Neo-Oli** [comment]
> does it work with plotext()?

Not sure what you mean by that. Is that a function of the module?

**Comment by piccolomo** [comment]
that was another typo 😉.

I meant plotsize(width, height) along size limitsize(False,False).

 hope it works

**Comment by Neo-Oli** [comment]
Ah, I know what the problem is. It is now depends on the order of operations.

This will create a big plot:
```
plt.limitsize(False,False)
plt.plotsize(200, 300)
```

And this will create the limited plot:
```
plt.plotsize(200, 300)
plt.limitsize(False,False)
```

In the previous version both snippets resulted in the same output. 

[Perhaps this should be documented.](https://github.com/piccolomo/plotext/blob/master/readme/aspect.md#plot-size)

**Comment by piccolomo** [comment]
Nicely spotted! I should add this to documentation. I will take a break for a while

**Comment by piccolomo** [comment]
I reopen this not to forget, to sort this out ...

**Comment by piccolomo** [comment]
Hi @Neo-Oli , 

I finally updated `plotext` including the changes you asked for. 

The new version is available [on GitHib](https://github.com/piccolomo/plotext) and soon also [on PyPi](https://pypi.org/project/plotext/). To install follow the indications [here](https://github.com/piccolomo/plotext#install).

Your changes are documented [here](https://github.com/piccolomo/plotext/blob/master/readme/settings.md#plot-size).

Thanks a lot for your inputs and all the best,
Savino
