### ISSUE TITLE
Braille pattern markers ⡠⠒⠊

### ISSUE THREAD

**Issue by Neo-Oli** [piccolomo/plotext#89]
Hey,

It would be very neat if we could have a marker option with unicode braille pattern. http://www.alanwood.net/unicode/braille_patterns.html

As far as I can tell they function very similarly to the current `fhd` markers and they should theoretically allow for an even greater resolution as they are 2x4 in scale (⣿)

```
______
|⠀⠀⡠⠀|
|⠤⠊⠀⠀|
|_____|
```

**Comment by piccolomo** [comment]
Hello @Neo-Oli   ,

I have added the `braille` marker as requested, in the new [version 5.1](https://github.com/piccolomo/plotext), available only on GitHub for now, using:
```console
pip install git+https://github.com/piccolomo/plotext
```
The marker is described [here](https://github.com/piccolomo/plotext/blob/master/readme/aspect.md#markers) and you have been credited [here](https://github.com/piccolomo/plotext/blob/master/readme/notes.md#credits).

Any feedback or double test is appreciated :-).
Thanks and all the best,
Savino

**Comment by Neo-Oli** [comment]
Oh wow, I tested it out and it works and looks great so far.
