### ISSUE TITLE
[by Author] Any Feedback, Opinion on Plotext welcomed here

### ISSUE THREAD

**Issue by piccolomo** [piccolomo/plotext#91]
Hello All,

I open this thread, to gather here **feedback** on the package of any kind: you could say whatever you want :-). 

Any new [color theme](https://github.com/piccolomo/plotext/blob/master/readme/aspect.md#colors) idea - or to change its silly names - for example is very welcomed. 

Anything you really don't like, or really like, or would rather change, or tweak.

Ideally those feedback could be used for next upgrade :-) 

Note: this is **not for issue reports** and **not for feature request**. Feel free to open an issue about it. 

All the best, 
Savino

**Comment by apiszcz** [comment]
.build() provides the commands for terminal to render the plot. Is there a method to obtain pure ascii representation of the plot so it will be printable, etc. in email/anywhere that is not a terminal?
Tx

**Comment by piccolomo** [comment]
Hi @apiszcz , thanks for stopping by and your feedback. This could help:
```python
import plotext as plt
#plt.clear_color() # to remove coloring from html version as well
plt.plotsize(100, 30) # chose size you prefer
plt.plot(plt.sin())
plot =plt.build() # plot is a string containing the plot with no colors and so no ansi escape codes
plt.savefig('test_plot.txt') # the plot is saved in home folder as colorless txt
plt.savefig('test_plot.html') # the plot is saved in home folder as colorful html
```
What do you think?

**Comment by apiszcz** [comment]
>>> df.A
0     17
1     74
2     36
3      3
4     36
5     85
6     34
7     88
8     24
9     18
10    32
11    93
12    31
13    12
14    64
Name: A, dtype: int32
>>> plt.plot(df.A)
>>> plot=plt.savefig('testplot.txt')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\g\via39\lib\lib\site-packages\plotext\_core.py", line 195, in save_fig
    figure.save_fig(path, keep_colors)
  File "C:\g\via39\lib\lib\site-packages\plotext\_figure.py", line 274, in save_fig
    ut.save_text(text, path)
  File "C:\g\via39\lib\lib\site-packages\plotext\_utility\file.py", line 23, in save_text
    file.write(text)
  File "C:\g\via39\lib\python\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 4-99: character maps to <undefined>

**Comment by piccolomo** [comment]
@apiszcz, could you post a workable code with orginal pandas dataframe?

**Comment by apiszcz** [comment]
df = pd.DataFrame(np.random.randint(0,100,size=(15, 4)), columns=list('ABCD'))

**Comment by piccolomo** [comment]
```python
import plotext as plt; import pandas as pd; import numpy as np
df = pd.DataFrame(np.random.randint(0,100,size=(15, 4)), columns=list('ABCD'))
#plt.clear_color() # to remove coloring from html version as well
plt.plotsize(100, 30) # chose size you prefer
plt.plot(df.A)
plot =plt.build() # plot is a string containing the plot, if you use clear_color() it won't contain ansi codes
plt.savefig('test_plot.txt') # the plot is saved in home folder as colorless txt
plt.savefig('test_plot.html') # the plot is saved in home folder as colorful html
```
what do you think?

**Comment by apiszcz** [comment]
I like the 'concept! :). The following test is on Windows 10, Python 3.9.

```
>>> df = pd.DataFrame(np.random.randint(0,100,size=(15, 4)), columns=list('ABCD'))
>>> #plt.clear_color() # to remove coloring from html version as well
>>> plt.plotsize(100, 30) # chose size you prefer
>>> plt.plot(df.A)
>>> plot =plt.build() # plot is a string containing the plot, if you use clear_color() it won't contain ansi codes
>>> plt.savefig('test_plot.txt') # the plot is saved in home folder as colorless txt
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\g\via39\lib\lib\site-packages\plotext\_core.py", line 195, in save_fig
    figure.save_fig(path, keep_colors)
  File "C:\g\via39\lib\lib\site-packages\plotext\_figure.py", line 274, in save_fig
    ut.save_text(text, path)
  File "C:\g\via39\lib\lib\site-packages\plotext\_utility\file.py", line 23, in save_text
    file.write(text)
  File "C:\g\via39\lib\python\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]


UnicodeEncodeError: 'charmap' codec can't encode characters in position 4-99: character maps to <undefined>
>>> plt.savefig('test_plot.html') # the plot is saved in home folder as colorful html
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\g\via39\lib\lib\site-packages\plotext\_core.py", line 195, in save_fig
    figure.save_fig(path, keep_colors)
  File "C:\g\via39\lib\lib\site-packages\plotext\_figure.py", line 274, in save_fig
    ut.save_text(text, path)
  File "C:\g\via39\lib\lib\site-packages\plotext\_utility\file.py", line 23, in save_text
    file.write(text)
  File "C:\g\via39\lib\python\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u250c' in position 474: character maps to <undefined>
```

**Comment by piccolomo** [comment]
Perhaps this deserves a separate issue, or we could continue in the old one you opened, which seems related.

**Comment by apiszcz** [comment]
it is related, my quest continues for a pure ASCII plot with the power you have developed for plotting! Thanks.

**Comment by piccolomo** [comment]
ok cool, I will try to solve it and post it to your old issue (if you agree), btw if you could send that code there, it would be great, otherwise i will find a way to do it. thanks a lot for the patience and great issue report. I may delete some posts here (or reduce them).

**Comment by apiszcz** [comment]
Yes, i agree.
The code is above from your sample, it demonstrates the issue.

```
import plotext as plt; import pandas as pd; import numpy as np
df = pd.DataFrame(np.random.randint(0,100,size=(15, 4)), columns=list('ABCD'))
 #plt.clear_color() # to remove coloring from html version as well
plt.plotsize(100, 30) # chose size you prefer
plt.plot(df.A)
plot =plt.build() # plot is a string containing the plot, if you use clear_color() it won't contain ansi codes
plt.savefig('test_plot.txt') # the plot is saved in home folder as colorless txt
```

**Comment by PhilipVinc** [comment]
Hi @piccolomo , I recently found out your library and I find it extremely useful to quickly plot data on a remote server..

If I could advance a feature request: error bars, at least along the y axis!

**Comment by piccolomo** [comment]
Hi @PhilipVinc, thanks for the nice message, I am happy that the project was useful to you :-). Error bar sounds like a cool idea and should not be too difficult to implement, as I have already built the `candlestick()` function which produces a similar result. 

I was thinking of an extra function like `error(x, errorx, errory)` to produce those cross shaped error bars. I will try to check if it can be done on both axes directions. I can tell that this request comes from a scientist (I was involved in quantum optics as well) :-).

**Comment by piccolomo** [comment]
Hello @PhilipVinc  ,

I added the error function as requested, in the new [version 5.1](https://github.com/piccolomo/plotext) available only on GitHub for now, using:

```console
pip install git+https://github.com/piccolomo/plotext
```
The function is described [here](https://github.com/piccolomo/plotext/blob/master/readme/other.md#error-plot) and you have been credited [here](https://github.com/piccolomo/plotext/blob/master/readme/notes.md#credits).

Any feedback or double test is appreciated.
Thanks and all the best,
Savino

**Comment by Chaitanyabsprip** [comment]
I there a way for me to make a box plot?

**Comment by Chaitanyabsprip** [comment]
I mean this way of plotting data.
https://towardsdatascience.com/understanding-boxplots-5e2df7bcbd51

basically the plot captures max, min, variance, median, mean and outliers of a dataset.

**Comment by piccolomo** [comment]
Hi Chaitanya, thanks for the clarification. What comes to mind is the error
plot
<https://github.com/piccolomo/plotext/blob/master/readme/other.md#error-plot>,
using the function error(), which you could probably adapt to your
situation using the xerr and yerr parameters, and also the candlestick()
function
<https://github.com/piccolomo/plotext/blob/master/readme/datetime.md#candlestick-plot>,
which I think accepts only dates as x values, and numbers for y values.
What do you think?
- Savino

**Comment by piccolomo** [comment]
Hi Chaitanya, thanks for the clarification. What comes to mind is the [error
plot](https://github.com/piccolomo/plotext/blob/master/readme/other.md#error-plot) which you could probably adapt to your situation using the `xerr` and `yerr` parameters, and also the [candlestick plot](https://github.com/piccolomo/plotext/blob/master/readme/datetime.md#candlestick-plot), which I think accepts only dates as `x` values, and numbers for `y` values.

What do you think?
- Savino

**Comment by eric8he** [comment]
Hey! 

Is there a way to only set one x- and y-limit? i.e. if you wanted the graph to be only in one quadrant.

**Comment by piccolomo** [comment]
Hi @eric8he ,

not sure if I understand correctly, but if I do you could use for example the function `xlim(upper = 3)` or `xlim(lower = 0)`,i.e. using only one parameter, or `xlim(lower = 0, upper = 3),` using both. The same thing applies for the function `ylim()` where the parameters are `left` and `right` this time. Did I get and answered your question?

**Comment by eric8he** [comment]
Thanks for the response!

Unfortunately, when I try only parameter in `xlim` or `ylim` I get this error:
<img width="1661" alt="Screen Shot 2022-08-02 at 11 16 20 AM" src="https://user-images.githubusercontent.com/19654278/182445332-432a8df2-25fd-4e85-8895-ace7850cf404.png">

**Comment by piccolomo** [comment]
mm that feels like a legit bug.. I shall fix this... bugs are piling up and may take some time (I am not working on `plotext` recently). If you need it quickly I guess you could test by modifying the code with `if None in xlim ` yourself for now. I will update anyway, but if you have any test done, feel free to share. all the best

**Comment by eric8he** [comment]
Yup! Replacing `xlim == [None] * 2` with `None in xlim` in monitor.py did the trick. Works well now. Thanks so much!!

**Comment by piccolomo** [comment]
my pleasure

**Comment by feizheng10** [comment]
plotext is definitely a cool tool! I'm wondering is it possible to add feature like drawing simple shapes with text/symbols in?

**Comment by piccolomo** [comment]
@feizheng10  Definitively something I may work for next version, may need time but thanks for your input.

**Comment by feizheng10** [comment]
> @feizheng10 Definitively something I may work for next version, may need time but thanks for your input.

To be honest, plotext is my favorite comparing to other text plot tools...but I need simple functionality like plotille canvas, which I believe would be useful for other projects want to build some describable blocks like flow chart.
Thanks for your quick response!

**Comment by piccolomo** [comment]
I deleted comments which were issue reports and feature requests, which are very much welcomed in separate issues. Here I leave it just for general feedback if useful.
