### ISSUE TITLE
Save plot to memory file?

### ISSUE THREAD

**Issue by apiszcz** [piccolomo/plotext#92]
Is it possible to save a plot to an in memory file fir savefig or some other method?

Trying this produces a stack trace:
```
f=io.Bytes()
pt.plot(data)
pt.savefig(f)
```

**Comment by apiszcz** [comment]
Solution:
pt.build()

thank you!

**Comment by piccolomo** [comment]
build() will output the string version of the figure, while savefig(path)
will save the plot in the path specified. you could try both. all the best
