### ISSUE TITLE
Bar Plot Limited Resolution Results in Wrong Bars

### ISSUE THREAD

**Issue by tweber68** [piccolomo/plotext#96]
I have the following values and keys for a horzizontal bar chart (value,key):

```
[(-0.6151373541529737, 42), (0.49192003213366264, 49), (0.42558999886357973, 89), (-0.4157197042616422, 52), (-0.4146001680909118, 37)]
```

My code is like this:
```
plt.clf()
plt.bar(keys, values, orientation = "horizontal", width = 1) # or shorter orientation = 'h'
plt.title('Strongest indexes in hidden layer (The following charts come in the same order)')
plt.plotsize(100, n + 4) # 4 = (1 for x numerical ticks + 2 for x axes + 1 for title)
plt.show()
```

The output is the following:
![image](https://user-images.githubusercontent.com/59922226/175299049-c2909bfb-eda7-4ef9-bb8f-4096897a756b.png)

You see I49 and I89 are not displayed correctly. They start in the negative area, which is not correct.

**Comment by piccolomo** [comment]
Hi @tweber68 ,

thanks for the report. 

I think the result is due to the limitation in character resolution. Here are three solutions using different markers and width (the other two are commented but work as well).

```
import plotext as plt

d = [(-0.6151373541529737, 42), (0.49192003213366264, 49), (0.42558999886357973, 89), (-0.4157197042616422, 52), (-0.4146001680909118, 37)]
values, keys = plt.transpose(d[::-1])
keys = ['I' + str(el) for el in keys]
n = len(keys)

plt.clf()
plt.bar(keys, values, orientation = "h", width = 0.1, marker = 'sd')
#plt.bar(keys, values, orientation = "h", width = 0.7, marker = 'hd')
#plt.bar(keys, values, orientation = "h", width = 0.5, marker = 'fhd')
plt.title('Strongest indexes in hidden layer (The following charts come in the same order)')
plt.plotsize(None, n + 4) # 4 = (1 for x numerical ticks + 2 for x axes + 1 for title)
plt.xticks(values)
plt.show()
```
![image](https://user-images.githubusercontent.com/56689657/175814572-3ccf7584-5fa2-48de-a919-41f187f7bca1.png)

What do you think?
All the best,
Savino

**Comment by piccolomo** [comment]
I reopen to remember to fix

**Comment by piccolomo** [comment]
Basically the each marker adds an extra width to each bar, and does affect the bar `width` parameter. I will try to find a way around this, that's why I reopened it.

**Comment by tweber68** [comment]
@piccolomo ok, thanks!

**Comment by tweber68** [comment]
@piccolomo In order to answer to your question: I think sd is more beautiful. Perhaps you could describe in the documentation what is a marker and how it is related to the option 'width'. I find this is not very clear.

Best, Theo

**Comment by piccolomo** [comment]
Hi @tweber68 , I finally updated `plotext`. 

I introduced simpler bar plots as described [here](https://github.com/piccolomo/plotext/blob/master/readme/bar.md). 

The new version is available [on GitHib](https://github.com/piccolomo/plotext) and soon also [on PyPi](https://pypi.org/project/plotext/). To install follow the indications [here](https://github.com/piccolomo/plotext#install).

This way the `marker` and `width` parameter won't interfere. Any feedback welcomed.

Thanks a lot for your inputs and all the best,
Savino

**Comment by tweber68** [comment]
@piccolomo Thanks for the information! Looks very good. I will try this in my applications. I will tell you. But I think this will work fine. :-)

**Comment by tweber68** [comment]
Hi @piccolomo,

I have just tested simple bar plots:
```
import plotext as plt

pizzas = ["Sausage", "Pepperoni", "Mushrooms", "Cheese", "Chicken", "Beef"]
percentages = [14, 36, -11, 8, -7, 4]

plt.simple_bar(pizzas, percentages, width = 100, title = 'Most Favored Pizzas in the World')
plt.show()
```

The output looks like:

![image](https://user-images.githubusercontent.com/59922226/200124127-8449068b-6095-4ee1-8a83-aeced54b35d0.png)

There are no bars for negative values. Is it intended?

**Comment by piccolomo** [comment]
Hi @tweber68, nicely spotted and thanks for reporting. I actually found this bug as well few days ago.

The solution is not straightforward and I was thinking to solve this for version 5.3 unless you need this solved quickly. 

Since this is a different bug from original, I will open another issue about it, for future reference, but if you want to do it yourself, no problem and would be grateful.

thanks again
Savino

**Comment by tweber68** [comment]
Hi @piccolomo, no, I don't need the fix at the moment. I just wanted to test it.

Besides, I find that plotext is really a great tool! For console applications, really really practical! Thanks a lot for doing this work.

**Comment by piccolomo** [comment]
> Hi @piccolomo, no, I don't need the fix at the moment. I just wanted to test it.
> 
> Besides, I find that plotext is really a great tool! For console applications, really really practical! Thanks a lot for doing this work.

appreciated ! 🙂
