### ISSUE TITLE
Weird Rendering of Sketchy Bar plot in Windows

### ISSUE THREAD

**Issue by newbiemate** [piccolomo/plotext#97]
The Sketchy Bar plot is messed up when rendered in Windows terminal:

https://github.com/piccolomo/plotext/blob/master/readme/bar.md#sketchy-bar-plot

Command:

    python3 -c "import plotext as plt; pizzas = ['Sausage', 'Pepperoni', 'Mushrooms', 'Cheese', 'Chicken', 'Beef']; percentages = [14, 36, 11, 8, 7, 4]; plt.bar(pizzas, percentages, orientation = 'h', width = 0.3, marker = 'fhd'); plt.title('Most Favoured Pizzas in the World'); plt.clc(); plt.plotsize(100, 2 * len(pizzas) + 4); plt.show()"

This is what I see:

![image](https://user-images.githubusercontent.com/34783617/176754019-9c2ca8a7-123b-40a8-b497-b5055a26cba7.png)

**Comment by piccolomo** [comment]
Thanks for reporting @newbiemate ! :-) 

mmm, you are right, try `marker = "hd"` or` marker = "sd"` inside the `bar()` function. I should explain those markers better in the guide.

Does it work?

**Comment by newbiemate** [comment]
Thanks,

Changing it to `marker='hd'` fixed it, but left a weird graphical artifact at one of the bar graphs:
![image](https://user-images.githubusercontent.com/34783617/176755684-b37baeec-726c-4f6f-a14a-d8e6ba42fff0.png)

Changing it to `marker='sd'` was correct but then I don't get the nice spacing:
![image](https://user-images.githubusercontent.com/34783617/176755766-ca585b1a-451e-4751-8119-0cb228e3ab98.png)

**Comment by piccolomo** [comment]
Also try `width = 0.2` inside the bar function when using `hd` marker. This is similar to [previous issue](https://github.com/piccolomo/plotext/issues/96), yet to be solved: each marker adds an extra width which is different from marker to marker.

**Comment by newbiemate** [comment]
Using `marker=hd` and `width = 0.2` fixed it all:

![image](https://user-images.githubusercontent.com/34783617/176757984-969a0355-8091-42d8-b66f-9ff49b39cf75.png)

Thank you! 

Do you have plans on getting 5.1 to pip? Currently it looks like it's on 5.0.2.

**Comment by piccolomo** [comment]
Actually I still see those weird coloring on the right side, try install version 5.1 with `pip install git+https://github.com/piccolomo/plotext` ... 

I would rather come up with a very well oiled new version, before publishing it on pypi... issues reports like yours are very helpful for this... also I am in a lazy/busy period and my mind is on something else, after last version (which was a big change from version 4).

**Comment by piccolomo** [comment]
Hi @pieterbergmans, I finally updated `plotext` including [new bar plots](https://github.com/piccolomo/plotext/blob/master/readme/bar.md), which should solve the issue. 

The new version is available [on GitHib](https://github.com/piccolomo/plotext) and soon also [on PyPi](https://pypi.org/project/plotext/). To install follow the indications [here](https://github.com/piccolomo/plotext#install).

Thanks a lot for your inputs and all the best,
Savino
