### ISSUE TITLE
Request: Sketchy Stacked Bar Plot

### ISSUE THREAD

**Issue by newbiemate** [piccolomo/plotext#98]
Hi, I like the Sketchy Bar feel of rendering the graph directly within the terminal. But I also would love to be able to stack multiple data on a single bar graph using different colors like you have for the Stacked Bar Plot.

An example is:
![image](https://user-images.githubusercontent.com/34783617/176758991-508a8588-7c6c-4630-9599-d761a2409062.png)

[Image source](https://github.com/mkaz/termgraph)

So in the Sketchy Bar Plot example, it would be nice to specify the Beef, Chicken, Cheese, Mushrooms, etc as a single bar with different colors stacked on top of each other.

**Comment by piccolomo** [comment]
That is one cool bar plot... I will try my best to answer this issue in the following days... thanks as usual for the inputs! :-)

**Comment by piccolomo** [comment]
Thinking out loud that it may better to have a dedicated function called `sketchy_bar()` and `sketchy_stacked_bar()` or similar to plot something like that easily without having to sett all the parameters manually, like text, dimension, etc ...

**Comment by piccolomo** [comment]
Hi @newbiemate,

I am finally working on your idea. Here is a temporary result for stacked bar plot.
![image](https://user-images.githubusercontent.com/56689657/187735444-536af5ed-bacd-43dd-8392-8a3d10801a5b.png)

And here is for multiple bar plot:
![image](https://user-images.githubusercontent.com/56689657/187735654-f96ecb37-02c3-4937-bef3-7a1689bdeb6b.png)

What do you think?

Thanks a lot for feedback

**Comment by piccolomo** [comment]
An update: added title and labels

![image](https://user-images.githubusercontent.com/56689657/187774778-9b7178b2-62e7-4b88-8ac5-cf3a6aed03ee.png)

**Comment by piccolomo** [comment]
Hi @newbiemate, I finally updated `plotext` including the changes you asked for. 

I introduced new sketchier bar functions documented [here](https://github.com/piccolomo/plotext/blob/master/readme/bar.md).

The new version is available [on GitHib](https://github.com/piccolomo/plotext) for now and soon also [on PyPi](https://pypi.org/project/plotext/). To install follow the indications [here](https://github.com/piccolomo/plotext#install).

You have been credited [here](https://github.com/piccolomo/plotext/blob/master/readme/notes.md#credits).

Any feedback is welcomed.

Thanks a lot for your inputs and all the best,
Savino
